/**
 * English dictionary. Typed against the Korean key set, so every key must exist here.
 * Tone: light, friendly, a little cheeky — never mocking the player.
 */
import type { StringKey } from './ko';

export const en: Record<StringKey, string> = {
  // --- common -------------------------------------------------------------
  'common.confirm': 'OK',
  'common.cancel': 'Cancel',
  'common.back': 'Back',
  'common.select': 'Select',
  'common.close': 'Close',
  'common.on': 'On',
  'common.off': 'Off',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.locked': 'Locked',
  'common.random': 'Random',
  'common.points': '{value} pts',
  'common.loading': 'Loading…',
  'common.continue': 'Continue',
  'common.vs': 'VS',
  'common.new': 'NEW',

  // --- prompt bar -----------------------------------------------------------
  'prompt.select': 'Select',
  'prompt.back': 'Back',
  'prompt.tabs': 'Switch tab',
  'prompt.adjust': 'Adjust',
  'prompt.navigate': 'Move',
  'prompt.skip': 'Skip',
  'prompt.equip': 'Wear',
  'prompt.rebind': 'Rebind',

  // --- title ----------------------------------------------------------------
  'game.title': '뿌리째 털어라',
  'game.titleEn': 'UPROOT HEIST',
  'game.tagline': 'While you grabbed a little safe, your buddy brought back the whole bank.',
  'title.pressAny': 'Press any key',
  'title.version': 'v{version}',

  // --- main menu ------------------------------------------------------------
  'menu.practice': 'Practice',
  'menu.practice.desc': 'Learn to grab, haul and recover in 50 seconds. Skip it any time.',
  'menu.quickMatch': 'Quick Match',
  'menu.quickMatch.desc': 'Pick a mode, layout and rival and jump right in. Everything is unlocked from the start.',
  'menu.tournament': 'Rival Tournament',
  'menu.tournament.desc': 'Hodadak → Tongkeun → Nunchi. Beat all three rivals, best of three each.',
  'menu.wardrobe': 'Wardrobe',
  'menu.wardrobe.desc': 'Try on the hats you won from your rivals. Cosmetics never change stats.',
  'menu.settings': 'Settings',
  'menu.settings.desc': 'Make the controls, sound and screen feel just right.',
  'menu.quit': 'Quit',
  'menu.quit.desc': "That's enough heisting for today. See you soon!",
  'menu.quitConfirm.title': 'Quit the game?',
  'menu.quitConfirm.body': 'Your progress is saved.',
  'menu.quitConfirm.ok': 'Quit',

  // --- modes / difficulty ---------------------------------------------------
  'mode.1v1': '1v1',
  'mode.2v2': '2v2',
  'mode.1v1.desc': 'You vs. one rival',
  'mode.2v2.desc': 'You + a buddy bot vs. two rivals',
  'mode.practice': 'Practice',
  'mode.quickMatch': 'Quick Match',
  'mode.tournament': 'Rival Tournament',
  'difficulty.novice': 'Rookie',
  'difficulty.normal': 'Normal',
  'difficulty.challenge': 'Challenge',
  'difficulty.novice.desc': 'Thinks slowly and reacts late.',
  'difficulty.normal.desc': 'Reads the room and switches targets.',
  'difficulty.challenge.desc': 'Pounces on every opening.',
  'difficulty.note': 'Difficulty only changes how fast bots think. Strength and speed are the same for everyone.',

  // --- quick match setup ----------------------------------------------------
  'quick.title': 'Quick Match',
  'quick.subtitle': 'Pick, then go heist!',
  'quick.mode': 'Mode',
  'quick.layout': 'Layout',
  'quick.opponent': 'Rival',
  'quick.difficulty': 'Difficulty',
  'quick.start': 'Start!',
  'quick.randomLayout': 'Random layout',
  'quick.randomLayout.desc': 'One of the three layouts, revealed before the match.',
  'quick.randomRival': 'Random rival',
  'quick.randomRival.desc': "You'll see who shows up before the match starts.",
  'quick.habit': 'Usual plan',
  'quick.weakness': 'Weak spot',
  'quick.total': '{value} pts on the field',

  // --- layouts (fallbacks; LAYOUT_STRINGS overrides) ------------------------
  'layout.random': 'Random',
  'layout.plaza.name': 'Collector Plaza',
  'layout.plaza.desc': 'Outer small safes are close by, but the wide road for hauling a bank is a bit long.',
  'layout.shortcut.name': 'Shortcut Arcade',
  'layout.shortcut.desc': 'Ram a fence with a bank to open a safe-hauling shortcut. Who opens it first?',
  'layout.counter.name': 'Open Counter',
  'layout.counter.desc': 'Bank doors face the busy crossroads. Guard the door, or empty it first?',
  'layout.tutorial.name': 'Practice Yard',
  'layout.tutorial.desc': 'One safe, one bank, one van. Take it easy and warm up.',

  // --- teams / names / loot ---------------------------------------------------
  'team.star': 'Star Crew',
  'team.moon': 'Moon Crew',
  'team.mine': 'Your team',
  'team.rival': 'Rival team',
  'name.you': 'You',
  'name.ally': 'Buddy Bot',
  'loot.smallSafe.name': 'Small safe',
  'loot.largeSafe.name': 'Big safe',
  'loot.bank.name': 'Bank',
  'loot.bankWall': 'Bank wall',
  'loot.emptyBank': 'Empty bank',

  // --- rivals (doc §11) -----------------------------------------------------
  'rival.hodadak.name': 'Hodadak',
  'rival.tongkeun.name': 'Tongkeun',
  'rival.nunchi.name': 'Nunchi',
  'rival.hodadak.title': 'The Speedy Snatcher',
  'rival.tongkeun.title': 'The Big Hauler',
  'rival.nunchi.title': 'The Opportunist',
  'rival.hodadak.personality': 'Zips to the nearest safes and recovers early and often.',
  'rival.tongkeun.personality': 'Drags whole banks home, safes and all.',
  'rival.nunchi.personality': 'Waits until you are stuck hauling something big, then swoops in.',
  'rival.hodadak.weakness': 'Claim the crossroads on its favorite route first.',
  'rival.tongkeun.weakness': 'Slip in through an open door and steal the safes inside.',
  'rival.nunchi.weakness': 'While it is busy harassing you, recover something else.',
  'rival.hodadak.intro': "Ready? 'Cause I already left!",
  'rival.tongkeun.intro': 'Small stuff is boring. Whole bank or nothing!',
  'rival.nunchi.intro': "You do the heavy lifting. I'll just watch~ Probably.",

  // --- rival adaptation lines --------------------------------------------------
  'adapt.hodadak.ambushChoke.1': "You like the {choke} route too, huh? This time I'll get there first!",
  'adapt.hodadak.ambushChoke.2': "Think I'll keep an eye on {choke} this round. Zoom!",
  'adapt.hodadak.ambushChoke.3': "We kept bumping into each other at {choke}… I'll be waiting there.",
  'adapt.tongkeun.ambushChoke.1': "I'll plug {choke} with my big self. Get past me if you can!",
  'adapt.tongkeun.ambushChoke.2': "Banks can wait. This round I'm watching {choke}.",
  'adapt.tongkeun.ambushChoke.3': 'I saw you hauling safes through {choke}. All of them!',
  'adapt.nunchi.ambushChoke.1': 'You sure go through {choke} a lot. I was watching~',
  'adapt.nunchi.ambushChoke.2': 'Maybe this time I keep an eye on that alley… {choke}?',
  'adapt.nunchi.ambushChoke.3': "If I wait at {choke}, something good will roll my way, right?",
  'adapt.hodadak.stripBank.1': "I saw you take a whole bank! This time I'm grabbing the big safe first.",
  'adapt.hodadak.stripBank.2': "Before you haul it off, I'll pull the safes out myself!",
  'adapt.hodadak.stripBank.3': "The safes in that bank? I'm zipping in for them first!",
  'adapt.tongkeun.stripBank.1': "A whole bank? You're bolder than me! This time I'm emptying it first.",
  'adapt.tongkeun.stripBank.2': "Hmm, whole-bank hauls, huh… then I'll grab the big safe inside first!",
  'adapt.tongkeun.stripBank.3': "Copying my signature move? I'll be waiting at the bank door.",
  'adapt.nunchi.stripBank.1': "The doors were wide open while you dragged that bank. I'm coming in~",
  'adapt.nunchi.stripBank.2': "I know you're going for the bank. I'll just slip the big safe out.",
  'adapt.nunchi.stripBank.3': "Dragging a bank must be tiring. Let me lighten the load~",
  'adapt.hodadak.guardDoors.1': "You snuck my safes out, didn't you? I'm guarding the door this time!",
  'adapt.hodadak.guardDoors.2': "Coming in through the bank door? Not this round. I'll be quick!",
  'adapt.hodadak.guardDoors.3': "I'll be right at the door. Just try to get in!",
  'adapt.tongkeun.guardDoors.1': "Walking in and taking my safes… This time I guard the doors first!",
  'adapt.tongkeun.guardDoors.2': "Hands off my bank! I'm blocking the doors this round.",
  'adapt.tongkeun.guardDoors.3': "The door is my spot now. Come in if you can!",
  'adapt.nunchi.guardDoors.1': "Saw you sneak in through the door~ This time I'm watching it.",
  'adapt.nunchi.guardDoors.2': "I know your way in now. I'll wait by the door~",
  'adapt.nunchi.guardDoors.3': 'Stealing my trick? Then I guess I guard the door this time.',
  'adapt.hint.ambushChoke': 'Try a different route, or the other bank.',
  'adapt.hint.stripBank': 'Use an empty bank, hit the other branch, or guard the doors.',
  'adapt.hint.guardDoors': 'Collect other targets, or come in through the opposite exit.',
  'adapt.none': 'No special plan this round. Business as usual.',

  // --- tournament -------------------------------------------------------------
  'tournament.title': 'Rival Tournament',
  'tournament.subtitle': 'Beat three rivals in a row. Each one is best of three!',
  'tournament.state.locked': 'Locked',
  'tournament.state.available': 'Ready',
  'tournament.state.inProgress': 'In progress',
  'tournament.state.cleared': 'Cleared!',
  'tournament.lockedHint': 'Beat the previous rival to unlock.',
  'tournament.reward': 'Reward',
  'tournament.bestOf3': 'Best of 3',
  'tournament.layout': 'Layout',
  'tournament.challenge': 'Challenge',
  'tournament.resume': 'Continue',
  'tournament.rechallenge': 'Rematch',
  'tournament.complete': 'Champion! You beat all three rivals.',
  'tournament.drawNote': "Draws don't count. You just play again.",
  'tournament.round': 'Round {n}',

  // --- series / intermission ----------------------------------------------------
  'series.game': 'Game {n}',
  'series.you': 'You',
  'series.score': 'Series',
  'series.firstTo2': 'First to 2 wins',
  'series.matchPoint': 'Match point!',
  'series.won': 'Series won!',
  'series.lost': 'Series lost',
  'intermission.title': 'Next Game',
  'intermission.rivalSays': '{rival} says',
  'intermission.hintTitle': 'Try switching it up',
  'intermission.next': 'Start next game',
  'intermission.quit': 'Tournament menu',
  'intermission.sameLayout': 'Same layout, next round.',

  // --- wardrobe -------------------------------------------------------------------
  'wardrobe.title': 'Wardrobe',
  'wardrobe.subtitle': 'Cosmetics never change stats. Wear what you love!',
  'wardrobe.equip': 'Wear',
  'wardrobe.equipped': 'Wearing',
  'wardrobe.locked': 'Locked',
  'wardrobe.teamNote': 'Your team emblem badge stays on, whatever you wear.',
  'wardrobe.collected': '{n}/{total} collected',
  'hat.none.name': 'No Hat',
  'hat.teamCapA.name': 'Pointy Star Beanie',
  'hat.teamCapB.name': 'Round Moon Helmet',
  'hat.hodadakBand.name': "Hodadak's Headband",
  'hat.tongkeunHat.name': "Tongkeun's Grand Top Hat",
  'hat.nunchiMask.name': "Nunchi's Eye Mask",
  'hat.none.desc': 'A nice breeze. Ears stay cool.',
  'hat.teamCapA.desc': "The Star Crew's classic. The star on top goes boing.",
  'hat.teamCapB.desc': "The Moon Crew's classic. That ring really shines.",
  'hat.hodadakBand.desc': 'You feel faster just wearing it! (Only the feeling.)',
  'hat.tongkeunHat.desc': 'Big enough to fit a bank. Makes you feel generous.',
  'hat.nunchiMask.desc': 'Symbol of the sharpest eyes in town. Shh.',
  'hat.none.unlock': 'Available from the start.',
  'hat.teamCapA.unlock': 'Available from the start.',
  'hat.teamCapB.unlock': 'Available from the start.',
  'hat.hodadakBand.unlock': 'Beat Hodadak in the Rival Tournament.',
  'hat.tongkeunHat.unlock': 'Beat Tongkeun in the Rival Tournament.',
  'hat.nunchiMask.unlock': 'Beat Nunchi in the Rival Tournament.',

  // --- settings -----------------------------------------------------------------------
  'settings.title': 'Settings',
  'settings.tab.game': 'Game',
  'settings.tab.controls': 'Controls',
  'settings.tab.audio': 'Audio',
  'settings.tab.display': 'Display',
  'settings.language': 'Language',
  'settings.grabMode': 'Grab mode',
  'settings.grabMode.hold': 'Hold',
  'settings.grabMode.toggle': 'Toggle',
  'settings.grabMode.desc': 'Hold: let go of the button to release. Toggle: press once to grab, again to release.',
  'settings.tutorialHints': 'Show hints',
  'settings.tutorialHints.desc': 'Short tips during practice and matches.',
  'settings.controls.action': 'Action',
  'settings.controls.keyboard': 'Keyboard',
  'settings.controls.gamepad': 'Gamepad',
  'settings.controls.pressKey': 'Press a key',
  'settings.controls.pressButton': 'Press a button',
  'settings.controls.unbound': 'None',
  'settings.controls.reset': 'Reset to defaults',
  'settings.controls.resetConfirm.title': 'Reset controls to defaults?',
  'settings.controls.resetConfirm.body': 'All your key and button changes will be undone.',
  'settings.controls.resetConfirm.ok': 'Reset',
  'settings.controls.hint': 'Pick a slot, then press the new key or button.',
  'settings.controls.swapped': 'That input was already used by “{action}”, so the two swapped.',
  'settings.controls.swappedTag': 'Swapped',
  'settings.controls.conflict': 'The same input is set for two actions. Change one of them.',
  'settings.controls.conflictTag': 'Clash',
  'settings.audio.master': 'Master volume',
  'settings.audio.music': 'Music',
  'settings.audio.sfx': 'Sound effects',
  'settings.audio.ui': 'Menu sounds',
  'settings.subtitles': 'Subtitles',
  'settings.subtitles.desc': 'Shows important sounds as text, like [Siren].',
  'settings.fullscreen': 'Fullscreen',
  'settings.quality': 'Graphics quality',
  'settings.screenShake': 'Screen shake',
  'settings.reducedMotion': 'Reduce motion',
  'settings.reducedMotion.desc': 'Tones down menu animations and screen effects.',
  'settings.uiScale': 'UI size',
  'settings.vibration': 'Vibration',
  'quality.low': 'Low',
  'quality.medium': 'Medium',
  'quality.high': 'High',
  'lang.ko': '한국어',
  'lang.en': 'English',

  // --- controls / actions -------------------------------------------------------------
  'action.moveUp': 'Move up',
  'action.moveDown': 'Move down',
  'action.moveLeft': 'Move left',
  'action.moveRight': 'Move right',
  'action.grab': 'Grab / Release',
  'action.dash': 'Dash',
  'action.ping': 'Ping',
  'action.pause': 'Pause',
  'hint.move': 'Move',
  'hint.grab': 'Grab',
  'hint.release': 'Release',
  'hint.dash': 'Dash',
  'hint.ping': 'Ping',
  'hint.pause': 'Pause',
  'hint.grabHold': 'Hold the button to keep holding on.',
  'hint.grabToggle': 'Press once to grab, again to let go.',
  'hint.dashFree': 'Empty-handed: a quick lunge that shoves rivals.',
  'hint.dashCarry': 'While holding: gives your load a quick burst.',
  'hint.pingTarget': 'Ping a safe or bank for "Grab together!", the ground for "This way!".',

  // --- pause ------------------------------------------------------------------------------
  'pause.title': 'Paused',
  'pause.resume': 'Resume',
  'pause.settings': 'Settings',
  'pause.restart': 'Restart',
  'pause.menu': 'Main menu',
  'pause.restartConfirm.title': 'Start over?',
  'pause.restartConfirm.body': "This match's scores will be lost.",
  'pause.restartConfirm.ok': 'Restart',
  'pause.menuConfirm.title': 'Leave to the menu?',
  'pause.menuConfirm.body': 'The current match will end here.',
  'pause.menuConfirm.ok': 'Leave',

  // --- results ----------------------------------------------------------------------------
  'results.win': 'Victory!',
  'results.lose': 'Defeat',
  'results.draw': 'Draw',
  'results.win.sub': 'You recovered more!',
  'results.lose.sub': 'Empty-handed this time… try a different plan?',
  'results.draw.sub': 'Dead even! One more?',
  'results.confirmed': 'Banked score',
  'results.biggest': 'Biggest moment',
  'results.noEvent': 'A quiet one this time.',
  'results.reason.time': "Time's up",
  'results.reason.allRecovered': 'All loot recovered',
  'results.reason.decided': 'Ended early: no comeback possible',
  'results.rematch': 'Rematch',
  'results.next': 'Next game',
  'results.menu': 'Menu',
  'results.series': 'Series {me} : {rival}',
  'results.drawReplay': "Draws don't count. Same layout, one more time!",
  'results.reward': 'New hat: {hat}',

  // --- result event phrases ------------------------------------------------------------------
  'event.smallRecovered': 'Small safe recovered +{value}',
  'event.largeRecovered': 'Big safe recovered +{value}',
  'event.bankWhole': 'Whole bank recovered! Building {building} + Safes {safes} = +{total}',
  'event.bankEmpty': 'Empty bank recovered! Building +{building}',
  'event.largePulled': 'A {value}-pt big safe was pulled out of a bank',
  'event.smallPulled': 'A {value}-pt small safe was pulled out of a bank',
  'event.lastSecondsSmall': 'Small safe recovered with {sec}s left',
  'event.lastSecondsLarge': 'Big safe recovered with {sec}s left',
  'event.lastSecondsBank': 'Whole bank recovered with {sec}s left! +{total}',
  'event.bankStolen': 'Stole a bank mid-haul and recovered it! +{total}',
  'event.stolenSafeRecovered': 'Recovered a big safe stolen from a bank +{value}',
  'event.fenceBankRecovered': 'Smashed through a fence and recovered the whole bank! +{total}',
  'event.comeback': 'Came back from {deficit} pts down',
  'event.finalCountdownBank': 'Second bank recovered: getaway countdown! +{total}',

  // --- HUD ------------------------------------------------------------------------------------
  'hud.confirmed': 'Banked',
  'hud.carrying': 'Carrying',
  'hud.estimate': 'Est. {value}',
  'hud.carryNote': 'Recover it to bank it',
  'hud.bankBreakdown': 'Building {building} + Safes {safes}',
  'hud.grab': 'Grab',
  'hud.release': 'Release',
  'hud.anchored': 'Pull {sec}s to uproot',
  'hud.uprooting': 'Uprooting…',
  'hud.dash': 'Dash',
  'hud.dashReady': 'Ready!',
  'hud.ping': 'Ping',
  'hud.you': 'You',
  'hud.ours': 'Us',
  'hud.timeLeft': 'Time left',
  'hud.banks': 'Banks',
  'hud.bankInPlay': 'In play',
  'hud.bankTaken': '{team} took it',
  'hud.banksCount': '{n}/{total} recovered',
  'hud.practice': 'Practice',
  'hud.practiceScore': 'Practice score',
  'hud.practiceNote': "Doesn't count toward matches",
  'hud.noLimit': 'No time limit',
  'hud.ping.grabTogether': 'Grab together!',
  'hud.ping.goHere': 'This way!',
  'hud.recovering': 'Recovering',
  'hud.loaded': 'Loaded',
  'hud.zone': 'Our van',

  // --- banners / popups ---------------------------------------------------------------------
  'banner.escape': 'Van leaves in {sec}s!',
  'banner.escape.sub': 'Both banks recovered. Getaway time!',
  'banner.lastBank': 'Recover it and the getaway begins',
  'banner.go': 'Go!',
  'banner.timeUp': "Time's up!",
  'banner.decided': 'Match decided!',
  'banner.allRecovered': 'Everything recovered!',
  'banner.practiceDone': 'Practice complete!',
  'popup.bank': 'Building {building} + Safes {safes} = +{total}',
  'popup.bankEmpty': 'Empty bank +{total}',

  // --- tutorial / practice --------------------------------------------------------------------
  'tutorial.label': 'Practice',
  'tutorial.skip': 'Skip practice',
  'tutorial.step': '{step}/{total}',
  'tutorial.find': 'Find the 100-pt small safe and your getaway van',
  'tutorial.find.sub': 'Safes are what you take. The spot in front of your van is where they go.',
  'tutorial.grabSafe': 'Walk up to the small safe and grab it',
  'tutorial.grabSafe.sub': 'Whatever you can grab lights up first.',
  'tutorial.bring': 'Drag it into the recovery zone by your van',
  'tutorial.bring.sub': 'Points are banked only once you recover it.',
  'tutorial.recovered': '+100! Those points are banked',
  'tutorial.recovered.sub': 'Nobody can take banked points away.',
  'tutorial.bankGrab': "Now grab the bank's outer wall",
  'tutorial.bankGrab.sub': 'Aim at a wall instead of a safe and the whole bank lights up.',
  'tutorial.uproot': 'Pull for 3 seconds to uproot the bank',
  'tutorial.uproot.sub': 'Once uprooted, anyone can drag it.',
  'tutorial.fence': 'Push the bank from behind to bust the fence',
  'tutorial.fence.sub': 'Pull from the front and you hit the fence first. Get behind the bank and shove it into the weak fence.',
  'tutorial.bankRecover': 'Recover the whole bank and the safes inside count too!',
  'tutorial.bankRecover.sub': 'You get the building 500 plus every safe loaded inside.',
  'tutorial.dash': 'Dash: a quick lunge, or a burst while hauling',
  'tutorial.dash.sub': 'Dash recharges every 4 seconds.',
  'tutorial.done': 'Nice work! Now your first match vs. a Rookie bot',
  'tutorial.done.sub': 'Practice points reset to 0 when the match starts.',

  // --- layout preview ---------------------------------------------------------------------------
  'preview.title': 'Layout Preview',
  'preview.sameInfo': 'Both teams see the same map',
  'preview.legend.zone': 'Recovery zone',
  'preview.legend.van': 'Getaway van',
  'preview.legend.bank': 'Bank · door side',
  'preview.legend.smallSafe': 'Small safe 100',
  'preview.legend.largeSafe': 'Big safe 300',
  'preview.legend.fence': 'Bank-breakable fence',
  'preview.startsIn': 'Starting soon',
  'preview.skip': 'Start now',
  'preview.total': '{value} pts total',

  // --- loading / tips -------------------------------------------------------------------------
  'loading.title': 'Heading to the plaza…',
  'loading.tip': 'Tip',
  'tip.1': 'Uprooting a safe scores nothing. Bring it to your van to bank it!',
  'tip.2': 'Safes loaded on a bank floor are recovered together with the bank.',
  'tip.3': 'While a rival drags a bank, slip in the door and steal the big safe.',
  'tip.4': 'Once both banks are recovered, the getaway van leaves in 30 seconds.',
  'tip.5': 'Dash recharges every 4 seconds. Shoves and carry bursts share it.',
  'tip.6': "Teammates can't knock each other down with a dash.",
  'tip.7': 'Banked points can never be taken away.',
  'tip.8': 'Equal scores mean a draw. Last touch never decides the winner.',
  'tip.9': 'One ping does both: "Grab together!" on loot, "This way!" on the ground.',
  'tip.10': 'Small safes fit through narrow alleys. Banks need the wide roads.',

  // --- dialogs / toasts --------------------------------------------------------------------------
  'toast.achievement': 'Achievement unlocked!',
  'toast.hat': 'New hat!',
  'toast.hat.body': 'Try it on in the Wardrobe',

  // --- achievements -------------------------------------------------------------------------------
  'ach.FIRST_RECOVERY.name': 'First Haul',
  'ach.FIRST_RECOVERY.desc': 'Recover loot and bank points for the first time.',
  'ach.BANK_WHOLE.name': 'Roots and All',
  'ach.BANK_WHOLE.desc': 'Recover an entire bank at your van.',
  'ach.BANK_HEIST_TEAM.name': 'Lift With Your Buddy',
  'ach.BANK_HEIST_TEAM.desc': 'Recover a bank together with your teammate in 2v2.',
  'ach.STEAL_LARGE.name': 'Smooth Extraction',
  'ach.STEAL_LARGE.desc': 'Steal a big safe out of a bank your rival was hauling, then recover it.',
  'ach.FENCE_BREAKER.name': 'I Make My Own Road',
  'ach.FENCE_BREAKER.desc': 'Break a fence with a bank.',
  'ach.LAST_SECONDS.name': 'Just in Time',
  'ach.LAST_SECONDS.desc': 'Complete a recovery in the final 5 seconds of a match.',
  'ach.COMEBACK.name': 'Comeback Kid',
  'ach.COMEBACK.desc': 'Win after trailing by more than 500 points.',
  'ach.BEAT_HODADAK.name': 'Caught Hodadak',
  'ach.BEAT_HODADAK.desc': 'Beat Hodadak in the Rival Tournament.',
  'ach.BEAT_TONGKEUN.name': 'Out-hauled Tongkeun',
  'ach.BEAT_TONGKEUN.desc': 'Beat Tongkeun in the Rival Tournament.',
  'ach.BEAT_NUNCHI.name': 'Outsmarted Nunchi',
  'ach.BEAT_NUNCHI.desc': 'Beat Nunchi in the Rival Tournament.',
  'ach.TOURNAMENT_CLEAR.name': 'Legend of the Plaza',
  'ach.TOURNAMENT_CLEAR.desc': 'Beat all three rivals and win the tournament.',
  'ach.WARDROBE.name': 'Dapper Raccoon',
  'ach.WARDROBE.desc': 'Wear a hat you won from a rival.',

  // --- captions ------------------------------------------------------------------------------------
  'caption.siren': '[Siren]',
  'caption.unanchorBank': '[Foundations snapping]',
  'caption.unanchorSafe': '[Safe pops loose]',
  'caption.fenceBreak': '[Fence crashing]',
  'caption.scoreBank': '[Bank recovered fanfare]',
  'caption.scoreSmall': '[Clink! Small safe recovered]',
  'caption.scoreLarge': '[Thunk! Big safe recovered]',
  'caption.dashHit': '[Whump!]',
  'caption.whistleStart': '[Starting whistle]',
  'caption.hornEnd': '[Final horn]',
  'caption.knockdown': '[Thud]',
  'caption.strain': '[Straining]',
  'caption.safeLoad': '[Safe loaded]',
  'caption.safeUnload': '[Safe slides out]',
  'caption.recoverStart': '[Recovery starts]',
  'caption.recoverCancel': '[Recovery cancelled]',
  'caption.countdownBeep': '[Beep]',
  'caption.victory': '[Victory music]',
  'caption.defeat': '[Wistful music]',
  'caption.draw': '[Draw music]',
  'caption.ping': '[Ping]',
  'caption.eject': '[Pop! Tossed outside]',
  'caption.bump': '[Bonk]',
  'caption.grab': '[Grab]',
  'caption.release': '[Let go]',
  'caption.dash': '[Whoosh]',
  'caption.bankRumble': '[Bank scraping along]',
  'caption.drag': '[Scraping]',
  'caption.sirenLoop': '[Siren continues]',

  // --- game flow (integration) -------------------------------------------------------------------
  'name.rivalBot': 'Rival bot',
  'event.fenceBroken': 'A bank busted the fence and opened a shortcut',
  'tutorial.wander': 'Head for the sparkly target. The arrows show the way.',
  'tutorial.wanderBank': 'Out the north gate, then follow the arrows round to the back of the bank.',
  'tutorial.regrab': 'Grab the bank wall again. Let go and the bank stops.',
  'tutorial.frontPull': 'Pulling from the front, you hit the fence first. Go round the back and push.',
  'tutorial.offer.title': 'Practice done. Ready for a real match?',
  'tutorial.offer.body': 'A 1v1 against beginner Hodadak on the plaza. Scores start from zero.',
  'tutorial.offer.match': 'First match vs a beginner bot',
  'tutorial.offer.menu': 'Main menu',
  'firstRun.title': 'Welcome, new raccoon',
  'firstRun.body': 'Want a 50-second practice to learn grabbing, hauling and recovering? You can skip it any time.',
  'firstRun.ok': 'Practice',
  'firstRun.later': 'Look around first',
  'error.title': 'Oops, something slipped',
  'error.body': 'Your game is still here. Try again, or head back to the menu.',
  'error.retry': 'Try again',
  'error.menu': 'Main menu',
  'error.detail': 'Your game is still here. Try again, or head back to the menu. (Error: {message})',
  'tournament.lockedPick': 'Beat the previous rival first.',
};
