/**
 * English dictionary. Typed against the Korean key set, so every key must exist here.
 * Tone: light, friendly, a little cheeky — never mocking the player.
 */
import type { StringKey } from './ko';

export const en: Record<StringKey, string> = {
  // --- common -------------------------------------------------------------
  'common.confirm': 'OK',
  'common.cancel': 'Cancel',
  'common.back': 'Back',
  'common.select': 'Select',
  'common.close': 'Close',
  'common.on': 'On',
  'common.off': 'Off',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.locked': 'Locked',
  'common.random': 'Random',
  'common.points': '{value} pts',
  'common.loading': 'Loading…',
  'common.continue': 'Continue',
  'common.vs': 'VS',
  'common.new': 'NEW',

  // --- prompt bar -----------------------------------------------------------
  'prompt.select': 'Select',
  'prompt.back': 'Back',
  'prompt.tabs': 'Switch tab',
  'prompt.adjust': 'Adjust',
  'prompt.navigate': 'Move',
  'prompt.skip': 'Skip',
  'prompt.equip': 'Wear',
  'prompt.rebind': 'Rebind',

  // --- title ----------------------------------------------------------------
  'game.title': '뿌리째 털어라',
  'game.titleEn': 'UPROOT HEIST',
  'game.tagline': 'While you grabbed a little safe, your buddy brought back the whole bank.',
  'title.pressAny': 'Press any key',
  'title.version': 'v{version}',

  // --- main menu ------------------------------------------------------------
  'menu.practice': 'Practice',
  'menu.practice.desc': 'Learn to grab, haul and recover in 50 seconds. Skip it any time.',
  'menu.quickMatch': 'Quick Match',
  'menu.quickMatch.desc': 'Pick a mode, layout and rival and jump right in. Everything is unlocked from the start.',
  'menu.tournament': 'Rival Tournament',
  'menu.tournament.desc': 'Hodadak → Tongkeun → Nunchi. Beat all three rivals, best of three each.',
  'menu.wardrobe': 'Wardrobe',
  'menu.wardrobe.desc': 'Try on the hats you won from your rivals. Cosmetics never change stats.',
  'menu.settings': 'Settings',
  'menu.settings.desc': 'Make the controls, sound and screen feel just right.',
  'menu.quit': 'Quit',
  'menu.quit.desc': "That's enough heisting for today. See you soon!",
  'menu.quitConfirm.title': 'Quit the game?',
  'menu.quitConfirm.body': 'Your progress is saved.',
  'menu.quitConfirm.ok': 'Quit',

  // --- modes / difficulty ---------------------------------------------------
  'mode.1v1': '1v1',
  'mode.2v2': '2v2',
  'mode.1v1.desc': 'You vs. one rival',
  'mode.2v2.desc': 'You + a buddy bot vs. two rivals',
  'mode.practice': 'Practice',
  'mode.quickMatch': 'Quick Match',
  'mode.tournament': 'Rival Tournament',
  'difficulty.novice': 'Rookie',
  'difficulty.normal': 'Normal',
  'difficulty.challenge': 'Challenge',
  'difficulty.novice.desc': 'Thinks slowly and reacts late.',
  'difficulty.normal.desc': 'Reads the room and switches targets.',
  'difficulty.challenge.desc': 'Pounces on every opening.',
  'difficulty.note': 'Difficulty only changes how fast bots think. Strength and speed are the same for everyone.',

  // --- quick match setup ----------------------------------------------------
  'quick.title': 'Quick Match',
  'quick.mode': 'Mode',
  'quick.layout': 'Layout',
  'quick.opponent': 'Rival',
  'quick.difficulty': 'Difficulty',
  'quick.start': 'Start!',
  'quick.randomLayout': 'Random layout',
  'quick.randomLayout.desc': 'One of the three layouts, revealed before the match.',
  'quick.randomRival': 'Random rival',
  'quick.randomRival.desc': "You'll see who shows up before the match starts.",
  'quick.habit': 'Usual plan',
  'quick.weakness': 'Weak spot',
  'quick.total': '{value} pts on the field',

  // --- layouts (fallbacks; LAYOUT_STRINGS overrides) ------------------------
  'layout.random': 'Random',
  'layout.plaza.name': 'Collector Plaza',
  'layout.plaza.desc': 'Outer small safes are close by, but the wide road for hauling a bank is a bit long.',
  'layout.shortcut.name': 'Shortcut Arcade',
  'layout.shortcut.desc': 'Ram a fence with a bank to open a safe-hauling shortcut. Who opens it first?',
  'layout.counter.name': 'Open Counter',
  'layout.counter.desc': 'Bank doors face the busy crossroads. Guard the door, or empty it first?',
  'layout.tutorial.name': 'Practice Yard',
  'layout.tutorial.desc': 'One safe, one bank, one van. Take it easy and warm up.',

  // --- teams / names / loot ---------------------------------------------------
  'team.star': 'Star Crew',
  'team.moon': 'Moon Crew',
  'team.mine': 'Your team',
  'team.rival': 'Rival team',
  'name.you': 'You',
  'name.ally': 'Buddy Bot',
  'loot.smallSafe.name': 'Small safe',
  'loot.largeSafe.name': 'Big safe',
  'loot.bank.name': 'Bank',
  'loot.bankWall': 'Bank wall',
  'loot.emptyBank': 'Empty bank',

  // --- rivals (doc §11) -----------------------------------------------------
  'rival.hodadak.name': 'Hodadak',
  'rival.tongkeun.name': 'Tongkeun',
  'rival.nunchi.name': 'Nunchi',
  'rival.hodadak.title': 'The Speedy Snatcher',
  'rival.tongkeun.title': 'The Big Hauler',
  'rival.nunchi.title': 'The Opportunist',
  'rival.hodadak.personality': 'Zips to the nearest safes and recovers early and often.',
  'rival.tongkeun.personality': 'Drags whole banks home, safes and all.',
  'rival.nunchi.personality': 'Waits until you are stuck hauling something big, then swoops in.',
  'rival.hodadak.weakness': 'Claim the crossroads on its favorite route first.',
  'rival.tongkeun.weakness': 'Slip in through an open door and steal the safes inside.',
  'rival.nunchi.weakness': 'While it is busy harassing you, recover something else.',
  'rival.hodadak.intro': "Ready? 'Cause I already left!",
  'rival.tongkeun.intro': 'Small stuff is boring. Whole bank or nothing!',
  'rival.nunchi.intro': "You do the heavy lifting. I'll just watch~ Probably.",

  // --- rival adaptation lines --------------------------------------------------
  'adapt.hodadak.ambushChoke.1': "You like the {choke} route too, huh? This time I'll get there first!",
  'adapt.hodadak.ambushChoke.2': "Think I'll keep an eye on {choke} this round. Zoom!",
  'adapt.hodadak.ambushChoke.3': "We kept bumping into each other at {choke}… I'll be waiting there.",
  'adapt.tongkeun.ambushChoke.1': "I'll plug {choke} with my big self. Get past me if you can!",
  'adapt.tongkeun.ambushChoke.2': "Banks can wait. This round I'm watching {choke}.",
  'adapt.tongkeun.ambushChoke.3': 'I saw you hauling safes through {choke}. All of them!',
  'adapt.nunchi.ambushChoke.1': 'You sure go through {choke} a lot. I was watching~',
  'adapt.nunchi.ambushChoke.2': 'Maybe this time I keep an eye on that alley… {choke}?',
  'adapt.nunchi.ambushChoke.3': "If I wait at {choke}, something good will roll my way, right?",
  'adapt.hodadak.stripBank.1': "I saw you take a whole bank! This time I'm grabbing the big safe first.",
  'adapt.hodadak.stripBank.2': "Before you haul it off, I'll pull the safes out myself!",
  'adapt.hodadak.stripBank.3': "The safes in that bank? I'm zipping in for them first!",
  'adapt.tongkeun.stripBank.1': "A whole bank? You're bolder than me! This time I'm emptying it first.",
  'adapt.tongkeun.stripBank.2': "Hmm, whole-bank hauls, huh… then I'll grab the big safe inside first!",
  'adapt.tongkeun.stripBank.3': "Copying my signature move? I'll be waiting at the bank door.",
  'adapt.nunchi.stripBank.1': "The doors were wide open while you dragged that bank. I'm coming in~",
  'adapt.nunchi.stripBank.2': "I know you're going for the bank. I'll just slip the big safe out.",
  'adapt.nunchi.stripBank.3': "Dragging a bank must be tiring. Let me lighten the load~",
  'adapt.hodadak.guardDoors.1': "You snuck my safes out, didn't you? I'm guarding the door this time!",
  'adapt.hodadak.guardDoors.2': "Coming in through the bank door? Not this round. I'll be quick!",
  'adapt.hodadak.guardDoors.3': "I'll be right at the door. Just try to get in!",
  'adapt.tongkeun.guardDoors.1': "Walking in and taking my safes… This time I guard the doors first!",
  'adapt.tongkeun.guardDoors.2': "Hands off my bank! I'm blocking the doors this round.",
  'adapt.tongkeun.guardDoors.3': "The door is my spot now. Come in if you can!",
  'adapt.nunchi.guardDoors.1': "Saw you sneak in through the door~ This time I'm watching it.",
  'adapt.nunchi.guardDoors.2': "I know your way in now. I'll wait by the door~",
  'adapt.nunchi.guardDoors.3': 'Stealing my trick? Then I guess I guard the door this time.',
  'adapt.hint.ambushChoke': 'Try a different route, or the other bank.',
  'adapt.hint.stripBank': 'Use an empty bank, hit the other branch, or guard the doors.',
  'adapt.hint.guardDoors': 'Collect other targets, or come in through the opposite exit.',
  'adapt.none': 'No special plan this round. Business as usual.',

  // --- tournament -------------------------------------------------------------
  'tournament.title': 'Rival Tournament',
  'tournament.subtitle': 'Beat three rivals in a row. Each one is best of three!',
  'tournament.state.locked': 'Locked',
  'tournament.state.available': 'Ready',
  'tournament.state.inProgress': 'In progress',
  'tournament.state.cleared': 'Cleared!',
  'tournament.lockedHint': 'Beat the previous rival to unlock.',
  'tournament.reward': 'Reward',
  'tournament.bestOf3': 'Best of 3',
  'tournament.layout': 'Layout',
  'tournament.challenge': 'Challenge',
  'tournament.resume': 'Continue',
  'tournament.rechallenge': 'Rematch',
  'tournament.complete': 'Champion! You beat all three rivals.',
  'tournament.drawNote': "Draws don't count. You just play again.",
  'tournament.round': 'Round {n}',

  // --- series / intermission ----------------------------------------------------
  'series.game': 'Game {n}',
  'series.you': 'You',
  'series.score': 'Series',
  'series.firstTo2': 'First to 2 wins',
  'series.matchPoint': 'Match point!',
  'series.won': 'Series won!',
  'series.lost': 'Series lost',
  'intermission.title': 'Next Game',
  'intermission.rivalSays': '{rival} says',
  'intermission.hintTitle': 'Try switching it up',
  'intermission.next': 'Start next game',
  'intermission.quit': 'Tournament menu',
  'intermission.sameLayout': 'Same layout, next round.',

  // --- wardrobe -------------------------------------------------------------------
  'wardrobe.title': 'Wardrobe',
  'wardrobe.subtitle': 'Cosmetics never change stats. Wear what you love!',
  'wardrobe.equip': 'Wear',
  'wardrobe.equipped': 'Wearing',
  'wardrobe.locked': 'Locked',
  'wardrobe.teamNote': 'Your team emblem badge stays on, whatever you wear.',
  'wardrobe.collected': '{n}/{total} collected',
  'hat.none.name': 'No Hat',
  'hat.teamCapA.name': 'Pointy Star Beanie',
  'hat.teamCapB.name': 'Round Moon Helmet',
  'hat.hodadakBand.name': "Hodadak's Headband",
  'hat.tongkeunHat.name': "Tongkeun's Grand Top Hat",
  'hat.nunchiMask.name': "Nunchi's Eye Mask",
  'hat.none.desc': 'A nice breeze. Ears stay cool.',
  'hat.teamCapA.desc': "The Star Crew's classic. The star on top goes boing.",
  'hat.teamCapB.desc': "The Moon Crew's classic. That ring really shines.",
  'hat.hodadakBand.desc': 'You feel faster just wearing it! (Only the feeling.)',
  'hat.tongkeunHat.desc': 'Big enough to fit a bank. Makes you feel generous.',
  'hat.nunchiMask.desc': 'Symbol of the sharpest eyes in town. Shh.',
  'hat.none.unlock': 'Available from the start.',
  'hat.teamCapA.unlock': 'Available from the start.',
  'hat.teamCapB.unlock': 'Available from the start.',
  'hat.hodadakBand.unlock': 'Beat Hodadak in the Rival Tournament.',
  'hat.tongkeunHat.unlock': 'Beat Tongkeun in the Rival Tournament.',
  'hat.nunchiMask.unlock': 'Beat Nunchi in the Rival Tournament.',

  // --- settings -----------------------------------------------------------------------
  'settings.title': 'Settings',
  'settings.tab.game': 'Game',
  'settings.tab.controls': 'Controls',
  'settings.tab.audio': 'Audio',
  'settings.tab.display': 'Display',
  'settings.language': 'Language',
  'settings.grabMode': 'Grab mode',
  'settings.grabMode.hold': 'Hold',
  'settings.grabMode.toggle': 'Toggle',
  'settings.grabMode.desc': 'Hold: let go of the button to release. Toggle: press once to grab, again to release.',
  'settings.tutorialHints': 'Show hints',
  'settings.tutorialHints.desc': 'Short tips during practice and matches.',
  'settings.credits': 'Credits',
  'settings.credits.desc': 'Tools, fonts and the full license texts.',
  // --- credits / licenses ------------------------------------------------------
  'credits.title': 'Credits',
  'credits.sub': 'What this little heist is made of.',
  'credits.version': 'Version {version}',
  'credits.made.title': 'Made with',
  'credits.made.body': 'Made with three.js, Electron, steamworks.js',
  'credits.fonts.title': 'Fonts',
  'credits.fonts.body': 'Jua, Noto Sans KR — SIL Open Font License 1.1',
  'credits.art.title': 'Art & sound',
  'credits.art.body': 'Every model, pattern, tune and sound effect is made in code. Not a single outside image or audio file.',
  'credits.team.title': 'Made by',
  'credits.team.body': 'The Uproot Heist team, one bank at a time.',
  'credits.thanks.title': 'Thanks',
  'credits.thanks.body': 'To everyone who builds and shares open source, and to you, uprooting banks right now. Thank you!',
  'credits.licenses': 'Licenses',
  'credits.licenses.title': 'Licenses',
  'credits.licenses.sub': 'Full license texts of the third-party software and fonts in this game.',
  'credits.prompt.read': 'Read',
  'settings.controls.action': 'Action',
  'settings.controls.keyboard': 'Keyboard',
  'settings.controls.gamepad': 'Gamepad',
  'settings.controls.pressKey': 'Press a key',
  'settings.controls.pressButton': 'Press a button',
  'settings.controls.unbound': 'None',
  'settings.controls.reset': 'Reset to defaults',
  'settings.controls.resetConfirm.title': 'Reset controls to defaults?',
  'settings.controls.resetConfirm.body': 'All your key and button changes will be undone.',
  'settings.controls.resetConfirm.ok': 'Reset',
  'settings.controls.hint': 'Pick a slot, then press the new key or button.',
  'settings.controls.swapped': 'That input was already used by “{action}”, so the two swapped.',
  'settings.controls.swappedTag': 'Swapped',
  'settings.controls.conflict': 'The same input is set for two actions. Change one of them.',
  'settings.controls.conflictTag': 'Clash',
  'settings.audio.master': 'Master volume',
  'settings.audio.music': 'Music',
  'settings.audio.sfx': 'Sound effects',
  'settings.audio.ui': 'Menu sounds',
  'settings.subtitles': 'Subtitles',
  'settings.subtitles.desc': 'Shows important sounds as text, like [Siren].',
  'settings.fullscreen': 'Fullscreen',
  'settings.quality': 'Graphics quality',
  'settings.screenShake': 'Screen shake',
  'settings.reducedMotion': 'Reduce motion',
  'settings.reducedMotion.desc': 'Tones down menu animations and screen effects.',
  'settings.uiScale': 'UI size',
  'settings.vibration': 'Vibration',
  'quality.low': 'Low',
  'quality.medium': 'Medium',
  'quality.high': 'High',
  'lang.ko': '한국어',
  'lang.en': 'English',

  // --- controls / actions -------------------------------------------------------------
  'action.moveUp': 'Move up',
  'action.moveDown': 'Move down',
  'action.moveLeft': 'Move left',
  'action.moveRight': 'Move right',
  'action.grab': 'Grab / Release',
  'action.dash': 'Dash',
  'action.ping': 'Ping',
  'action.pause': 'Pause',
  'hint.move': 'Move',
  'hint.grab': 'Grab',
  'hint.release': 'Release',
  'hint.dash': 'Dash',
  'hint.ping': 'Ping',
  'hint.pause': 'Pause',
  'hint.grabHold': 'Hold the button to keep holding on.',
  'hint.grabToggle': 'Press once to grab, again to let go.',
  'hint.dashFree': 'Empty-handed: a quick lunge that shoves rivals.',
  'hint.dashCarry': 'While holding: gives your load a quick burst.',
  'hint.pingTarget': 'Ping a safe or bank for "Grab together!", the ground for "This way!".',

  // --- pause ------------------------------------------------------------------------------
  'pause.title': 'Paused',
  'pause.resume': 'Resume',
  'pause.settings': 'Settings',
  'pause.restart': 'Restart',
  'pause.menu': 'Main menu',
  'pause.restartConfirm.title': 'Start over?',
  'pause.restartConfirm.body': "This match's scores will be lost.",
  'pause.restartConfirm.ok': 'Restart',
  'pause.menuConfirm.title': 'Leave to the menu?',
  'pause.menuConfirm.body': 'The current match will end here.',
  'pause.menuConfirm.ok': 'Leave',

  // --- results ----------------------------------------------------------------------------
  'results.win': 'Victory!',
  'results.lose': 'Defeat',
  'results.draw': 'Draw',
  'results.win.sub': 'You recovered more!',
  'results.lose.sub': 'Empty-handed this time… try a different plan?',
  'results.draw.sub': 'Dead even! One more?',
  'results.confirmed': 'Banked score',
  'results.biggest': 'Biggest moment',
  'results.noEvent': 'A quiet one this time.',
  'results.reason.time': "Time's up",
  'results.reason.allRecovered': 'All loot recovered',
  'results.reason.decided': 'Ended early: no comeback possible',
  'results.rematch': 'Rematch',
  'results.next': 'Next game',
  'results.menu': 'Menu',
  'results.series': 'Series {me} : {rival}',
  'results.drawReplay': "Draws don't count. Same layout, one more time!",
  'results.reward': 'New hat: {hat}',

  // --- result event phrases ------------------------------------------------------------------
  'event.smallRecovered': 'Small safe recovered +{value}',
  'event.largeRecovered': 'Big safe recovered +{value}',
  'event.bankWhole': 'Whole bank recovered! Building {building} + Safes {safes} = +{total}',
  'event.bankEmpty': 'Empty bank recovered! Building +{building}',
  'event.largePulled': 'A {value}-pt big safe was pulled out of a bank',
  'event.smallPulled': 'A {value}-pt small safe was pulled out of a bank',
  'event.lastSecondsSmall': 'Small safe recovered with {sec}s left',
  'event.lastSecondsLarge': 'Big safe recovered with {sec}s left',
  'event.lastSecondsBank': 'Whole bank recovered with {sec}s left! +{total}',
  'event.bankStolen': 'Stole a bank mid-haul and recovered it! +{total}',
  'event.stolenSafeRecovered': 'Recovered a big safe stolen from a bank +{value}',
  'event.fenceBankRecovered': 'Smashed through a fence and recovered the whole bank! +{total}',
  'event.comeback': 'Came back from {deficit} pts down',
  'event.finalCountdownBank': 'Second bank recovered: getaway countdown! +{total}',

  // --- HUD ------------------------------------------------------------------------------------
  'hud.confirmed': 'Banked',
  'hud.carrying': 'Carrying',
  'hud.estimate': 'Est. {value}',
  'hud.carryNote': 'Recover it to bank it',
  'hud.bankBreakdown': 'Building {building} + Safes {safes}',
  'hud.grab': 'Grab',
  'hud.release': 'Release',
  'hud.anchored': 'Pull {sec}s to uproot',
  'hud.uprooting': 'Uprooting…',
  'hud.dash': 'Dash',
  'hud.dashReady': 'Ready!',
  'hud.ping': 'Ping',
  'hud.you': 'You',
  'hud.ours': 'Us',
  'hud.timeLeft': 'Time left',
  'hud.banks': 'Banks',
  'hud.bankInPlay': 'In play',
  'hud.bankTaken': '{team} took it',
  'hud.banksCount': '{n}/{total} recovered',
  'hud.practice': 'Practice',
  'hud.practiceScore': 'Practice score',
  'hud.practiceNote': "Doesn't count toward matches",
  'hud.noLimit': 'No time limit',
  'hud.ping.grabTogether': 'Grab together!',
  'hud.ping.goHere': 'This way!',
  'hud.recovering': 'Recovering',
  'hud.loaded': 'Loaded',
  'hud.zone': 'Our van',

  // --- banners / popups ---------------------------------------------------------------------
  'banner.escape': 'Van leaves in {sec}s!',
  'banner.escape.sub': 'Both banks recovered. Getaway time!',
  'banner.lastBank': 'Recover it and the getaway begins',
  'banner.go': 'Go!',
  'banner.timeUp': "Time's up!",
  'banner.decided': 'Match decided!',
  'banner.allRecovered': 'Everything recovered!',
  'banner.practiceDone': 'Practice complete!',
  'popup.bank': 'Building {building} + Safes {safes} = +{total}',
  'popup.bankEmpty': 'Empty bank +{total}',

  // --- tutorial / practice --------------------------------------------------------------------
  'tutorial.label': 'Practice',
  'tutorial.skip': 'Skip practice',
  'tutorial.step': '{step}/{total}',
  'tutorial.find': 'Find the 100-pt small safe and your getaway van',
  'tutorial.find.sub': 'Safes are what you take. The spot in front of your van is where they go.',
  'tutorial.grabSafe': 'Walk up to the small safe and grab it',
  'tutorial.grabSafe.sub': 'Whatever you can grab lights up first.',
  'tutorial.bring': 'Drag it into the recovery zone by your van',
  'tutorial.bring.sub': 'Points are banked only once you recover it.',
  'tutorial.recovered': '+100! Those points are banked',
  'tutorial.recovered.sub': 'Nobody can take banked points away.',
  'tutorial.bankGrab': "Now grab the bank's outer wall",
  'tutorial.bankGrab.sub': 'Aim at a wall instead of a safe and the whole bank lights up.',
  'tutorial.uproot': 'Pull for 3 seconds to uproot the bank',
  'tutorial.uproot.sub': 'Once uprooted, anyone can drag it.',
  'tutorial.fence': 'Push the bank from behind to bust the fence',
  'tutorial.fence.sub': 'Pull from the front and you hit the fence first. Get behind the bank and shove it into the weak fence.',
  'tutorial.bankRecover': 'Recover the whole bank and the safes inside count too!',
  'tutorial.bankRecover.sub': 'You get the building 500 plus every safe loaded inside.',
  'tutorial.dash': 'Dash: a quick lunge, or a burst while hauling',
  'tutorial.dash.sub': 'Dash recharges every 4 seconds.',
  'tutorial.done': 'Nice work! Now your first match vs. a Rookie bot',
  'tutorial.done.sub': 'Practice points reset to 0 when the match starts.',

  // --- layout preview ---------------------------------------------------------------------------
  'preview.title': 'Layout Preview',
  'preview.sameInfo': 'Both teams see the same map',
  'preview.legend.zone': 'Recovery zone',
  'preview.legend.van': 'Getaway van',
  'preview.legend.bank': 'Bank · door side',
  'preview.legend.smallSafe': 'Small safe 100',
  'preview.legend.largeSafe': 'Big safe 300',
  'preview.legend.fence': 'Bank-breakable fence',
  'preview.startsIn': 'Starting soon',
  'preview.skip': 'Start now',
  'preview.total': '{value} pts total',

  // --- loading / tips -------------------------------------------------------------------------
  'loading.title': 'Heading to the plaza…',
  'loading.tip': 'Tip',
  'tip.1': 'Uprooting a safe scores nothing. Bring it to your van to bank it!',
  'tip.2': 'Safes loaded on a bank floor are recovered together with the bank.',
  'tip.3': 'While a rival drags a bank, slip in the door and steal the big safe.',
  'tip.4': 'Once both banks are recovered, the getaway van leaves in 30 seconds.',
  'tip.5': 'Dash recharges every 4 seconds. Shoves and carry bursts share it.',
  'tip.6': "Teammates can't knock each other down with a dash.",
  'tip.7': 'Banked points can never be taken away.',
  'tip.8': 'Equal scores mean a draw. Last touch never decides the winner.',
  'tip.9': 'One ping does both: "Grab together!" on loot, "This way!" on the ground.',
  'tip.10': 'Small safes fit through narrow alleys. Banks need the wide roads.',

  // --- dialogs / toasts --------------------------------------------------------------------------
  'toast.achievement': 'Achievement unlocked!',
  'toast.hat': 'New hat!',
  'toast.hat.body': 'Try it on in the Wardrobe',

  // --- achievements -------------------------------------------------------------------------------
  'ach.FIRST_RECOVERY.name': 'First Haul',
  'ach.FIRST_RECOVERY.desc': 'Recover loot and bank points for the first time.',
  'ach.BANK_WHOLE.name': 'Roots and All',
  'ach.BANK_WHOLE.desc': 'Recover an entire bank at your van.',
  'ach.BANK_HEIST_TEAM.name': 'Lift With Your Buddy',
  'ach.BANK_HEIST_TEAM.desc': 'Recover a bank together with your teammate in 2v2.',
  'ach.STEAL_LARGE.name': 'Smooth Extraction',
  'ach.STEAL_LARGE.desc': 'Steal a big safe out of a bank your rival was hauling, then recover it.',
  'ach.FENCE_BREAKER.name': 'I Make My Own Road',
  'ach.FENCE_BREAKER.desc': 'Break a fence with a bank.',
  'ach.LAST_SECONDS.name': 'Just in Time',
  'ach.LAST_SECONDS.desc': 'Complete a recovery in the final 5 seconds of a match.',
  'ach.COMEBACK.name': 'Comeback Kid',
  'ach.COMEBACK.desc': 'Win after trailing by more than 500 points.',
  'ach.BEAT_HODADAK.name': 'Caught Hodadak',
  'ach.BEAT_HODADAK.desc': 'Beat Hodadak in the Rival Tournament.',
  'ach.BEAT_TONGKEUN.name': 'Out-hauled Tongkeun',
  'ach.BEAT_TONGKEUN.desc': 'Beat Tongkeun in the Rival Tournament.',
  'ach.BEAT_NUNCHI.name': 'Outsmarted Nunchi',
  'ach.BEAT_NUNCHI.desc': 'Beat Nunchi in the Rival Tournament.',
  'ach.TOURNAMENT_CLEAR.name': 'Legend of the Plaza',
  'ach.TOURNAMENT_CLEAR.desc': 'Beat all three rivals and win the tournament.',
  'ach.WARDROBE.name': 'Dapper Raccoon',
  'ach.WARDROBE.desc': 'Wear a hat you won from a rival.',

  // --- captions ------------------------------------------------------------------------------------
  'caption.siren': '[Siren]',
  'caption.unanchorBank': '[Foundations snapping]',
  'caption.unanchorSafe': '[Safe pops loose]',
  'caption.fenceBreak': '[Fence crashing]',
  'caption.scoreBank': '[Bank recovered fanfare]',
  'caption.scoreSmall': '[Clink! Small safe recovered]',
  'caption.scoreLarge': '[Thunk! Big safe recovered]',
  'caption.dashHit': '[Whump!]',
  'caption.whistleStart': '[Starting whistle]',
  'caption.hornEnd': '[Final horn]',
  'caption.knockdown': '[Thud]',
  'caption.strain': '[Straining]',
  'caption.safeLoad': '[Safe loaded]',
  'caption.safeUnload': '[Safe slides out]',
  'caption.recoverStart': '[Recovery starts]',
  'caption.recoverCancel': '[Recovery cancelled]',
  'caption.countdownBeep': '[Beep]',
  'caption.victory': '[Victory music]',
  'caption.defeat': '[Wistful music]',
  'caption.draw': '[Draw music]',
  'caption.ping': '[Ping]',
  'caption.eject': '[Pop! Tossed outside]',
  'caption.bump': '[Bonk]',
  'caption.grab': '[Grab]',
  'caption.release': '[Let go]',
  'caption.dash': '[Whoosh]',
  'caption.bankRumble': '[Bank scraping along]',
  'caption.drag': '[Scraping]',
  'caption.sirenLoop': '[Siren continues]',

  // --- game flow (integration) -------------------------------------------------------------------
  'name.rivalBot': 'Rival bot',
  'event.fenceBroken': 'A bank busted the fence and opened a shortcut',
  'tutorial.wander': 'Head for the sparkly target. The arrows show the way.',
  'tutorial.wanderBank': 'Out the north gate, then follow the arrows round to the back of the bank.',
  'tutorial.regrab': 'Grab the bank wall again. Let go and the bank stops.',
  'tutorial.frontPull': 'Pulling from the front, you hit the fence first. Go round the back and push.',
  'tutorial.offer.title': 'Practice done. Ready for a real match?',
  'tutorial.offer.body': 'A 1v1 against beginner Hodadak on the plaza. Scores start from zero.',
  'tutorial.offer.match': 'First match vs a beginner bot',
  'tutorial.offer.menu': 'Main menu',
  'firstRun.title': 'Welcome, new raccoon',
  'firstRun.body': 'Want a 50-second practice to learn grabbing, hauling and recovering? You can skip it any time.',
  'firstRun.ok': 'Practice',
  'firstRun.later': 'Look around first',
  'error.title': 'Oops, something slipped',
  'error.body': 'Your game is still here. Try again, or head back to the menu.',
  'error.retry': 'Try again',
  'error.menu': 'Main menu',
  'error.detail': 'Your game is still here. Try again, or head back to the menu. (Error: {message})',
  'tournament.abandon.title': 'Drop the series in progress?',
  'tournament.abandon.body': 'Your record against {rival} in that series will be lost. Rivals you beat stay beaten.',
  'tournament.abandon.ok': 'Drop it and start',
  'tournament.lockedPick': 'Beat the previous rival first.',
  'adapt.none.hodadak': 'A plan? Nah! Same as always. Zoom zoom~',
  'adapt.none.tongkeun': 'Why change a winning plan? Whole bank again!',
  'adapt.none.nunchi': "Hmm~ I'll just do my usual thing. Still watching you, though.",
  'results.nextRival': 'Next rival',
  'results.toLadder': 'Tournament',
  'tournament.forfeit.body': 'Leaving a rival match now counts this game as a loss.',
  'police.dispatched.kicker': 'The alarm went off!',
  'police.dispatched.title': 'Police incoming!',
  'police.dispatched.body': 'They chase anyone carrying a safe or a bank. A dash knocks them over.',
  // --- UI overhaul: stamps, police HUD, 3D preview tags -------------------------
  'tournament.caught': "Got 'em!",
  'results.stamp.win': 'Victory!',
  'results.stamp.lose': 'So close!',
  'results.stamp.draw': 'Draw!',
  'stamp.uproot': 'Uprooted!',
  'stamp.steal': 'Stolen!',
  'stamp.bankWhole': 'Whole bank!',
  'stamp.dodge': 'Dodged!',
  'stamp.police': 'Cops!',
  'hud.policeIn': 'Police in {sec}s',
  'hud.policeOn': 'Police out · {n}',
  'banner.policeDispatched': 'Police dispatched!',
  'banner.policeDispatched.sub': 'A squad car is coming for anyone carrying loot!',
  'banner.policeArrived': 'Police are here!',
  'banner.policeArrived.sub': 'A dash knocks an officer right over!',
  'preview.legend.police': 'Police entry',
  'preview.ourVan': 'Our van',
  'preview.theirVan': 'Their van',
  'preview.tagBankParts': 'building + safes',
  'preview.policeEntry': 'Police entry',
  // --- police / presentation captions (mirrors src/audio/captions.ts fallbacks) ---
  'caption.uprootPop': '[Pop! Uprooted]',
  'caption.policeSiren': '[Police siren]',
  'caption.alarmBell': '[Bank alarm]',
  'caption.policeSkid': '[Screech! Police car pulls up]',
  'caption.policeWhistle': '[Whistle]',
  'caption.policeBark': '[Officer: "Stop!"]',
  'caption.tackle': '[Tackle!]',
  'caption.tackleMiss': '[Whoosh! Tackle misses]',
  'caption.policeStun': '[Boing! Officer knocked over]',
  'caption.policePhew': '[Phew! Police drive off]',
  'caption.tauntWiggle': '[toot-toot booty wiggle]',
  'caption.tauntBleh': '[raspberry blat]',
  'caption.tauntCash': '[cash fan flutter]',
  'caption.tauntSquat': '[boing boing]',
  'caption.tauntZoom': '[zoom]',
  'caption.tauntFlex': '[muscle sparkle]',
  'caption.tauntShrug': '[smug shrug]',

  // --- taunts (owner addition) ------------------------------------------------------------
  'action.emote1': 'Taunt 1 · Booty Wiggle',
  'action.emote2': 'Taunt 2 · Bleh!',
  'action.emote3': 'Taunt 3 · Cash Fan',
  'action.emote4': 'Taunt 4 · Squat Bounce',
  'action.emoteWheel': 'Taunt wheel (hold and pick)',
  'hint.emote': 'Taunt',
  'hint.emoteWheel': 'Taunt wheel',
  'hint.tauntNote': 'Stand still with empty paws to tease. Moving stops it.',
  'emote.wiggle.name': 'Booty Wiggle',
  'emote.bleh.name': 'Bleh!',
  'emote.fanCash.name': 'Cash Fan',
  'emote.squatBounce.name': 'Squat Bounce',
  'emote.hodadakZoom.name': 'Zoom Pose',
  'emote.tongkeunFlex.name': 'Flex',
  'emote.nunchiShrug.name': 'Smug Shrug',
  'emote.hodadakZoom.unlock': 'Beat Hodadak to unlock it.',
  'emote.tongkeunFlex.unlock': 'Beat Tongkeun to unlock it.',
  'emote.nunchiShrug.unlock': 'Beat Nunchi to unlock it.',
  'taunt.wheel.title': 'Taunt',
  'taunt.wheel.pick': 'Pick one, then let go',
  'taunt.wheel.release': 'Let go to taunt',
  'taunt.wheel.locked': 'Locked taunt',
  'taunt.wheel.blocked': 'Paws must be free',
  'taunt.nope.moving': 'Stop first, then tease!',
  'taunt.nope.cooling': 'Catching my breath…',
  'settings.showOthersTaunts': "Show other raccoons' taunts",
  'settings.showOthersTaunts.desc': "Off hides everyone else's taunt moves, bubbles and sounds. Yours still play.",
  // === Fun round string blocks (docs/ARCHITECTURE.md "Fun round contracts") ===
  // Each package adds keys ONLY between its own two markers, in ko.ts AND en.ts (same keys).
  // Never edit another package's block or move the markers.
  // --- [WP2] begin: taunt.bark.<BarkKey> (bot bark bubbles; one key per BARK_KEYS entry)
  // --- [WP2] end
  // --- [WP4] begin: hud.mp.* (hud.mp.ours / hud.mp.theirs: decisive-load prompt, also the WP3 world label), hud.moment.* (stamps; hud.moment.stealChance "빼내기 +{value}" is read by WP3)
  'hud.mp.ours': "Get this in and it's over!",
  'hud.mp.theirs': 'Stop that load!',
  'hud.mp.oursTie': "Get it in: it's a draw!",
  'hud.mp.theirsTie': 'Stop it or it ends in a draw!',
  'hud.mp.sub': 'Est. {value}',
  'hud.mp.subBag': 'Bag {value}',
  'hud.mp.subWithBag': 'Est. {value} · bag {bag} in it',
  'hud.mp.swing.behind': '{n} to take the lead',
  'hud.mp.swing.level': '{n} to go ahead',
  'hud.mp.swing.ahead': 'Ahead by {n}',
  'hud.mp.swing.remaining': '{m} left',
  'hud.moment.stealChance': 'Steal +{value}',
  'hud.moment.leadTaken': 'Lead change!',
  'hud.moment.equalized': 'All square!',
  'hud.moment.mpStopped': 'Stopped it!',
  'hud.moment.mpStoppedTheirs': 'Blocked!',
  'hud.moment.streak': '{value}-point run!',
  'hud.moment.streakBroken': 'Run broken!',
  'hud.moment.streakBrokenTheirs': 'Our run is over!',
  'hud.moment.tauntPunished': 'Taunt punished!',
  'hud.moment.dodged': 'Sidestepped!',
  'hud.moment.counterDash': 'Head-on!',
  'hud.moment.coinSplash': 'Shook loose {value}!',
  'hud.moment.coinSplashTheirs': 'Dropped {value} in coins!',
  'hud.moment.jackpot': 'Jackpot {value}!',
  'hud.moment.hammerBonk': 'Hammer bonk!',
  'hud.moment.hammerBonkTheirs': 'Got bonked!',
  'hud.moment.homeRun': 'Out of the park!',
  'hud.moment.goldHammer': 'Golden hammer!',
  'hud.moment.tossScore': 'Flung it home!',
  'hud.moment.craneDrop': 'Crane stopped!',
  'hud.moment.eventHaul': 'Event cleaned out!',
  'hud.moment.sub.bankWhole': 'Whole bank!',
  'hud.moment.sub.streak2': 'On fire!',
  'hud.moment.climaxBadge': 'Getaway!',
  // --- [WP4] end
  // --- [WP6] begin: results.hook.*, rivalLine.* (WP6 may also reword existing results.* keys in place)
  // --- [WP6] end
  // --- [WP7] begin: cup.*, onboard.* (cup tabs, first-hour strip, menu "이어서 / 다음 목표" card)
  // --- [WP7] end
  // --- [WP8] begin: caption.<newSfxId> (captions for every new cue)
  'caption.tensionHeartbeat': '[Thump-thump, match point heartbeat]',
  'caption.stingBlocked': '[Stab! Match point stopped]',
  'caption.stingLead': '[Fanfare run, the lead changes]',
  'caption.stingEqual': '[Ding-dong, scores level]',
  'caption.streakFill': '[Drum fill, scoring run]',
  'caption.streakScratch': '[Record scratch, run broken]',
  'caption.runClimb': '[Ting! The run goes on]',
  'caption.finalTick': '[Tick]',
  'caption.vanRev': '[Vroom, getaway van revving]',
  'caption.vanDriveOff': '[Vroom! Getaway van pulls away]',
  'caption.tauntPunish': '[Boing! Taunter bonked]',
  'caption.dodgeWhoosh': '[Whoosh! Dodged]',
  'caption.clashAccent': '[Ta! Head-on clash]',
  'caption.barkBlip': '[Rival hoots]',
  'caption.stingGoldHammer': '[Sparkle! Golden hammer has landed]',
  // --- [WP8] end
  // --- [WP10] begin: book.*, plus hat.<newHatId>.name/.desc/.unlock for the six new hats
  // --- [WP10] end
  // --- [C10] begin: front.* (front door, boot splash), news.* (news strip headlines; update notes live in public/news.json)
  'front.play': 'Play',
  'front.play.sub.quick': 'Quick Match · {mode} · {map}',
  'front.play.sub.first': 'New here? Start with a 50-second practice',
  'front.play.change': 'Change map & rival',
  'front.play.change.desc': 'Pick the map, rival and difficulty. Play keeps whatever you pick.',
  'front.menu.aria': 'Menu',
  'front.play.map.random': 'Random map',
  'front.play.desc': 'One press and you\'re in, with your last Quick Match setup.',
  'front.play.desc.first': 'First time? Practice first. It takes 50 seconds and you can skip it any time.',
  'front.player.aria': 'Your raccoon',
  'front.player.rank.0': 'Rookie Raider',
  'front.player.rank.1': 'Alley Raider',
  'front.player.rank.2': 'Mall Raider',
  'front.player.rank.3': 'Plaza Heist King',
  'front.goal.label': 'Next goal',
  'front.goal.continue': 'Continue',
  'front.goal.desc': 'Pick up where you left off, or try the next thing worth doing.',
  'front.goal.dismiss': 'Hide goal',
  'front.goal.dismiss.desc': 'Hide the goal for now. It comes back next time you start the game.',
  'front.goal.series': 'Finish the best of 3 vs {rival}',
  'front.goal.practice': 'Warm up with a 50-second practice',
  'front.goal.rival': 'Beat {rival} for a new hat',
  'front.credits': 'Credits',
  'front.credits.desc': 'The people and tools behind the heist.',
  'front.news.label': 'Plaza News',
  'front.boot.note': 'Contains flashing lights and fast motion. You can turn on Reduced Motion in Settings.',
  'front.boot.skip': 'Press any key to skip',
  'front.news.h01': 'Plaza bank vanishes, roots and all. Guard: "I was only at lunch"',
  'front.news.h02': 'Hodadak spooked by own shadow mid-heist',
  'front.news.h03': 'Tongkeun: "Small safes aren\'t even safes." Uproar follows',
  'front.news.h04': 'Nunchi slips a safe out of someone else\'s bank. Again',
  'front.news.h05': 'Shortcut Mall replaces its fence for the third time this week',
  'front.news.h06': 'Open Counter clerk: "Keep the counter open. Leave the bank, please"',
  'front.news.h07': 'Police siren becomes a raccoon fan anthem',
  'front.news.h08': 'Pigeon club: "We\'re tired of taking off every time a bank rolls by"',
  'front.news.h09': 'Plaza florist plants fresh flowers in the bank tracks',
  'front.news.h10': 'Raccoon van collects its 37th parking ticket',
  'front.news.h11': 'Cat at the window: "Saw it all. Not talking"',
  'front.news.h12': 'Reports say the bank alarm rings in time with the music',
  'front.news.h13': 'Safe maker: "Bolting it down was never the problem"',
  'front.news.h14': 'Another guard\'s lunchbox goes missing. Hungry raccoon suspected',
  'front.news.h15': 'Hodadak runs three hours a day: "Getting there first is the best part"',
  'front.news.h16': 'Tongkeun\'s top hat is in the wash. Bare head today',
  'front.news.h17': 'Nunchi interview: "You haul. I\'ll collect at the end"',
  'front.news.h18': 'Plaza fountain posts a sign: "Not a safe wash"',
  'front.news.h19': 'Pointy star beanies sold out across town',
  'front.news.h20': 'Bank landlord: "It never had wheels"',
  'front.news.h21': 'Too many draws? Raccoons say: "Just play another"',
  'front.news.h22': 'More safes than shoppers use the mall shortcut',
  'front.news.h23': 'Police repeat their rule: empty paws, no chase',
  'front.news.h24': 'Fresh paint for the recovery zone outside the van',
  'front.news.h25': 'Whole bank recovered. Ally bot: "I pushed too!"',
  'front.news.h26': 'Dash classes boom: "Who knew knocking folks over felt this good"',
  'front.news.h27': 'Plaza News reporter stubs a toe on a safe mid-report',
  'front.news.h28': 'Raccoon gridlock at the bank doors',
  'front.news.h29': 'Local bakery: "No, we won\'t make a donut-shaped safe"',
  'front.news.h30': 'Police car leaving late today. Reason: classified',
  'front.news.h31': 'Rooftop party noise complaint. The crew promises to keep it down',
  'front.news.h32': 'Safe-top snack table praised: "Sturdier than it looks"',
  'front.news.h33': 'Hodadak vs Tongkeun rematch? Insider: "One press away"',
  'front.news.h34': 'Rumour has it the clock ticks louder in the last 30 seconds',
  'front.news.h35': 'Nunchi: "Getaway? I always know first"',
  'front.news.h36': 'Expert tip: don\'t pull a bank from the front. Push it from behind',
  'front.news.h37': 'Rumour: the van only honks after a win',
  'front.news.h38': 'Today\'s weather: sunny, with the odd safe',
  'front.news.h39': 'Ally bot: "Lots of praise, never a hat"',
  'front.news.h40': 'Rooftop zipline safety rule: one raccoon at a time',
  // --- [C10] end
  // --- [C8] begin: hud.content.* (Content 2.0 HUD: item slot verbs, item / prop / breakable names, bag chip, deposit ring, item name tags)
  'hud.content.item.hammer.name': 'Squeaky hammer',
  'hud.content.item.hammer.verb': 'Bonk!',
  'hud.content.item.hammer.hint': 'Dash empty-handed to bonk!',
  'hud.content.item.goldHammer.name': 'Golden squeaky hammer',
  'hud.content.item.goldHammer.verb': 'BONK!',
  'hud.content.item.goldHammer.hint': 'Longer reach, bigger bonk!',
  'hud.content.item.plunger.name': 'Plunger',
  'hud.content.item.plunger.verb': 'Yank!',
  'hud.content.item.plunger.hint': 'Dash empty-handed to yank stuff over',
  'hud.content.item.skates.name': 'Rocket skates',
  'hud.content.item.skates.verb': 'Zoom!',
  'hud.content.item.skates.hint': 'Your dashes go way further',
  'hud.content.item.soap.name': 'Soap suds',
  'hud.content.item.soap.verb': 'Suds!',
  'hud.content.item.soap.hint': 'Dashing leaves a slippery trail',
  'hud.content.item.balloons.name': 'Balloon bunch',
  'hud.content.item.balloons.verb': 'Float!',
  'hud.content.item.balloons.hint': 'Grab loot to tie them on and lighten it',
  'hud.content.item.smoke.name': 'Sneeze cloud',
  'hud.content.item.smoke.verb': 'Achoo!',
  'hud.content.item.smoke.hint': 'Dash empty-handed to lob a cloud',
  'hud.content.item.incoming': 'Supply drop in {sec}',
  'hud.content.item.uses': '{n} left',
  'hud.content.prop.atm': 'ATM',
  'hud.content.prop.piggy': 'Piggy bank',
  'hud.content.prop.moneyTree': 'Money tree',
  'hud.content.prop.goldSafe': 'Gold safe',
  'hud.content.breakable.crate': 'Crate',
  'hud.content.breakable.vending': 'Gulp vending machine',
  'hud.content.tag.coins': 'Coins ×{n}',
  'hud.content.tag.bills': 'Bills ×{n}',
  'hud.content.tag.cracks': 'Cracks {n}/3',
  'hud.content.tag.kick': 'Kick it along',
  'hud.content.bag.label': 'Bag',
  'hud.content.bag.hint': 'Empty it at your van',
  'hud.content.bag.full': 'Full! Empty it at your van',
  'hud.content.bag.depositing': 'Emptying…',
  'hud.content.bag.deposited': 'Emptied!',
  'hud.content.bag.spilled': 'Spilled! -{value}',
  'hud.content.deposit': 'Deposit',
  // --- [C8] end
  // --- [F3] begin: beat.* (render beats: world labels the GameView draws; hud.mp.theirs / hud.moment.stealChance are WP4's)
  'beat.decisive.ours': 'Match point!',
  // --- [F3] end
  // --- [LOCAL] begin: local multiplayer
  'menu.together': 'Play Together',
  'mode.together': 'Play Together',
  'menu.together.desc': 'Up to four friends on one screen: two on one keyboard, plus up to four pads.',
  'quick.together': 'Play with friends',
  'together.title': 'Play Together',
  'together.sub': 'Press grab to join!',
  'together.joinHow': 'To join',
  'together.device.kbA': 'Keyboard left',
  'together.device.kbB': 'Keyboard right',
  'together.device.pad': 'Pad {n}',
  'together.device.anyPad': 'Pad',
  'together.openSeat': 'Open seat',
  'together.botSeat': 'A bot fills in',
  'together.readyHow': '{grab} ready · {dash} leave',
  'together.readyShort': 'Ready',
  'together.ready': 'Ready!',
  'together.style.none': 'Who’s in?',
  'together.style.versus': 'Versus!',
  'together.style.coop': 'Co-op!',
  'together.style.versus.desc': 'Star team vs moon team, friend vs friend',
  'together.style.coop.desc': 'All on one team: rob the bot team together',
  'together.count': '{humans} players · {bots} bots',
  'together.nobody': 'Nobody here yet',
  'together.waiting': 'Pick a team with ◀ ▶, grab to get ready. Once everyone is ready, pick the match.',
  'together.full': 'Two per team, tops',
  'together.optionsLater': 'Pick the match once everyone is ready',
  'together.size': 'Size',
  'together.difficulty': 'Bot level',
  'together.noBots': 'No bots, just us!',
  'together.start': 'Let’s rob!',
  'together.backToJoin': 'Joining',
  'together.remote': 'Online friends can hop in as pads with Steam Remote Play Together',
  'together.win': '{team} wins!',
  'together.draw': 'Draw!',
  'together.hl.title': 'Stars of the round',
  'together.hl.uproots': 'Most uproots',
  'together.hl.steals': 'Most steals',
  'together.hl.recovered': 'Most hauled home',
  'together.hl.none': 'Next round for sure!',
  'together.hl.count': '{n}×',
  'together.hl.value': '{value} pts',
  // --- [LOCAL] end
};
