/**
 * Korean dictionary (default language). Warm, playful 해요체.
 *
 * This object is the canonical key set: `en.ts` is typed against `keyof typeof ko`, so a key
 * missing from English is a compile error. Layout names/descriptions here are fallbacks only;
 * LAYOUT_STRINGS (src/sim/layouts/strings.ts) is merged on top and wins.
 *
 * Particle note: rival / chokepoint / team names are inserted as params. Lines are phrased so
 * no particle (은/는, 이/가, 을/를, 로/으로) directly follows a param.
 */
export const ko = {
  // --- common -------------------------------------------------------------
  'common.confirm': '확인',
  'common.cancel': '취소',
  'common.back': '뒤로',
  'common.select': '선택',
  'common.close': '닫기',
  'common.on': '켜짐',
  'common.off': '꺼짐',
  'common.yes': '네',
  'common.no': '아니요',
  'common.locked': '잠김',
  'common.random': '무작위',
  'common.points': '{value}점',
  'common.loading': '불러오는 중…',
  'common.continue': '계속',
  'common.vs': 'VS',
  'common.new': 'NEW',

  // --- prompt bar -----------------------------------------------------------
  'prompt.select': '선택',
  'prompt.back': '뒤로',
  'prompt.tabs': '탭 전환',
  'prompt.adjust': '조절',
  'prompt.navigate': '이동',
  'prompt.skip': '건너뛰기',
  'prompt.equip': '쓰기',
  'prompt.rebind': '바꾸기',

  // --- title ----------------------------------------------------------------
  'game.title': '뿌리째 털어라',
  'game.titleEn': 'UPROOT HEIST',
  'game.tagline': '작은 금고 챙기는 사이, 친구는 은행째 가져왔다.',
  'title.pressAny': '아무 키나 누르세요',
  'title.version': 'v{version}',

  // --- main menu ------------------------------------------------------------
  'menu.practice': '연습',
  'menu.practice.desc': '50초 만에 잡기·운반·회수를 익혀요. 언제든 건너뛸 수 있어요.',
  'menu.quickMatch': '빠른 대전',
  'menu.quickMatch.desc': '모드, 배치, 상대를 골라 바로 한 판! 모든 선택이 처음부터 열려 있어요.',
  'menu.tournament': '라이벌 대회',
  'menu.tournament.desc': '호다닥 → 통큰이 → 눈치왕. 3판 2선승으로 세 라이벌을 차례로 이겨 봐요.',
  'menu.wardrobe': '옷장',
  'menu.wardrobe.desc': '라이벌에게 얻은 모자를 써 봐요. 장식은 능력치를 바꾸지 않아요.',
  'menu.settings': '설정',
  'menu.settings.desc': '조작, 소리, 화면을 내 손에 꼭 맞게 바꿔요.',
  'menu.quit': '종료',
  'menu.quit.desc': '오늘의 털이는 여기까지. 또 만나요!',
  'menu.quitConfirm.title': '게임을 종료할까요?',
  'menu.quitConfirm.body': '진행 상황은 저장되어 있어요.',
  'menu.quitConfirm.ok': '종료',

  // --- modes / difficulty ---------------------------------------------------
  'mode.1v1': '1:1',
  'mode.2v2': '2:2',
  'mode.1v1.desc': '나 대 라이벌 한 명',
  'mode.2v2.desc': '나 + 동료 봇 대 라이벌 둘',
  'mode.practice': '연습',
  'mode.quickMatch': '빠른 대전',
  'mode.tournament': '라이벌 대회',
  'difficulty.novice': '입문',
  'difficulty.normal': '보통',
  'difficulty.challenge': '도전',
  'difficulty.novice.desc': '천천히 생각하고 늦게 반응해요.',
  'difficulty.normal.desc': '눈치껏 목표를 바꿔 가며 움직여요.',
  'difficulty.challenge.desc': '빈틈을 빠르게 파고들어요.',
  'difficulty.note': '난이도는 판단 속도만 바꿔요. 힘과 속도는 모두 똑같아요.',

  // --- quick match setup ----------------------------------------------------
  'quick.title': '빠른 대전',
  'quick.subtitle': '고르고, 바로 털러 가요!',
  'quick.mode': '모드',
  'quick.layout': '배치',
  'quick.opponent': '상대 성향',
  'quick.difficulty': '난이도',
  'quick.start': '시작!',
  'quick.randomLayout': '무작위 배치',
  'quick.randomLayout.desc': '세 배치 중 하나를 골라 시작 전에 공개해요.',
  'quick.randomRival': '무작위 상대',
  'quick.randomRival.desc': '세 라이벌 중 누가 나올지 시작 전에 알려 줘요.',
  'quick.habit': '평소 선택',
  'quick.weakness': '노릴 빈틈',
  'quick.total': '경기장 전체 {value}점',

  // --- layouts (fallbacks; LAYOUT_STRINGS overrides) ------------------------
  'layout.random': '무작위',
  'layout.plaza.name': '수집 광장',
  'layout.plaza.desc': '외곽의 작은 금고는 가깝고, 은행을 끌고 갈 넓은 길은 조금 멀어요.',
  'layout.shortcut.name': '지름길 상가',
  'layout.shortcut.desc': '은행으로 펜스를 뚫으면 금고 운반 길이 열려요. 길은 누가 열까요?',
  'layout.counter.name': '열린 창구',
  'layout.counter.desc': '은행 문이 모두가 지나는 교차로를 향해 있어요. 문을 지킬까, 먼저 빼낼까?',
  'layout.tutorial.name': '연습장',
  'layout.tutorial.desc': '금고 하나, 은행 하나, 우리 차 하나. 천천히 손을 풀어요.',

  // --- teams / names / loot ---------------------------------------------------
  'team.star': '별 팀',
  'team.moon': '달 팀',
  'team.mine': '우리 팀',
  'team.rival': '상대 팀',
  'name.you': '나',
  'name.ally': '동료 봇',
  'loot.smallSafe.name': '작은 금고',
  'loot.largeSafe.name': '큰 금고',
  'loot.bank.name': '은행',
  'loot.bankWall': '은행 외벽',
  'loot.emptyBank': '빈 은행',

  // --- rivals (doc §11) -----------------------------------------------------
  'rival.hodadak.name': '호다닥',
  'rival.tongkeun.name': '통큰이',
  'rival.nunchi.name': '눈치왕',
  'rival.hodadak.title': '발 빠른 소매치기',
  'rival.tongkeun.title': '통 큰 운반왕',
  'rival.nunchi.title': '가로채기의 달인',
  'rival.hodadak.personality': '가까운 금고부터 호다닥! 자주, 빨리 회수해요.',
  'rival.tongkeun.personality': '금고가 가득 든 은행을 통째로 끌고 가요.',
  'rival.nunchi.personality': '남이 큰 짐에 묶이면 슬쩍 다가와 가로채요.',
  'rival.hodadak.weakness': '자주 쓰는 길의 교차로를 먼저 차지해 보세요.',
  'rival.tongkeun.weakness': '열린 문으로 들어가 안의 금고를 빼내 보세요.',
  'rival.nunchi.weakness': '견제하느라 바쁠 때 다른 목표를 회수해 보세요.',
  'rival.hodadak.intro': '준비됐어? 난 벌써 출발했는데!',
  'rival.tongkeun.intro': '작은 건 시시해. 오늘도 통째로 간다!',
  'rival.nunchi.intro': '열심히 옮겨 줘. 나는 구경만 할게~ 아마도?',

  // --- rival adaptation lines (doc §11 다음 판; Adaptation.lineKey) -----------
  // ambushChoke: {choke} = chokepoint display name (pass the nameKey; t() resolves it).
  'adapt.hodadak.ambushChoke.1': '{choke} 쪽 길, 너도 좋아하더라? 이번엔 내가 먼저 가 있을게!',
  'adapt.hodadak.ambushChoke.2': '이번에는 {choke} 근처를 지켜볼까? 호다닥 달려갈게!',
  'adapt.hodadak.ambushChoke.3': '{choke}에서 자꾸 마주치던데… 이번엔 거기서 기다릴게.',
  'adapt.tongkeun.ambushChoke.1': '{choke} 길목은 내 큰 덩치로 막아 볼게. 지나갈 수 있으면 지나가 봐!',
  'adapt.tongkeun.ambushChoke.2': '은행은 잠깐 미뤄 두고, 이번엔 {choke} 쪽을 지켜볼까?',
  'adapt.tongkeun.ambushChoke.3': '{choke}에서 금고 들고 지나가는 거, 다 봤다고!',
  'adapt.nunchi.ambushChoke.1': '{choke} 쪽으로 자주 다니던데? 다 보고 있었지~',
  'adapt.nunchi.ambushChoke.2': '이번에는 그 골목, {choke} 근처를 지켜볼까?',
  'adapt.nunchi.ambushChoke.3': '{choke}에서 기다리면 뭔가 굴러들어 오겠지?',
  'adapt.hodadak.stripBank.1': '은행째 들고 가는 거 봤어! 이번엔 큰 금고부터 쏙 빼 갈게.',
  'adapt.hodadak.stripBank.2': '통째로 가져가기 전에 내가 먼저 금고를 꺼내 올 거야!',
  'adapt.hodadak.stripBank.3': '은행 안 금고, 이번엔 내가 먼저 호다닥 챙긴다!',
  'adapt.tongkeun.stripBank.1': '은행째 가져가다니, 나보다 통이 크네? 이번엔 금고부터 꺼내 둘게.',
  'adapt.tongkeun.stripBank.2': '흠, 은행 통째 회수라… 그럼 안에 든 큰 금고부터 챙겨야겠다!',
  'adapt.tongkeun.stripBank.3': '내 특기를 따라 하다니! 이번엔 은행 문 앞에서 기다릴게.',
  'adapt.nunchi.stripBank.1': '은행 끄는 동안 문이 활짝 열려 있던데? 이번엔 내가 들어갈게~',
  'adapt.nunchi.stripBank.2': '은행째 노리는 거 다 알아. 큰 금고만 쏙 빼 갈게.',
  'adapt.nunchi.stripBank.3': '무거운 은행 끄느라 힘들지? 안에 든 건 내가 들어 줄게~',
  'adapt.hodadak.guardDoors.1': '내 금고 몰래 빼 갔지? 이번엔 문 앞을 지킬 거야!',
  'adapt.hodadak.guardDoors.2': '은행 문으로 들어오는 거, 이번엔 호다닥 막을게!',
  'adapt.hodadak.guardDoors.3': '문 앞에서 기다릴게. 들어오기만 해 봐!',
  'adapt.tongkeun.guardDoors.1': '문으로 들어와서 금고를 빼 가다니… 이번엔 문부터 지킨다!',
  'adapt.tongkeun.guardDoors.2': '내 은행에 손대지 마! 이번엔 출입문을 꽉 막을 거야.',
  'adapt.tongkeun.guardDoors.3': '문 쪽은 이제 내 자리야. 들어올 수 있으면 들어와 봐!',
  'adapt.nunchi.guardDoors.1': '문으로 슬쩍 들어오는 거 봤지롱. 이번엔 문 앞에서 눈치 볼게.',
  'adapt.nunchi.guardDoors.2': '들어오는 길은 이제 다 알아. 문 앞에서 기다릴게~',
  'adapt.nunchi.guardDoors.3': '내가 하던 걸 네가 하다니! 이번엔 문을 지켜 볼까?',
  // What the player can switch to (doc §11 table, right column).
  'adapt.hint.ambushChoke': '다른 길이나 다른 은행을 써 보세요.',
  'adapt.hint.stripBank': '빈 은행 활용, 다른 지점 회수, 출입문 방어를 생각해 보세요.',
  'adapt.hint.guardDoors': '다른 목표를 모으거나 반대쪽 출구로 접근해 보세요.',
  'adapt.none': '이번 판은 특별한 대응 없이 평소처럼 움직일 거예요.',

  // --- tournament -------------------------------------------------------------
  'tournament.title': '라이벌 대회',
  'tournament.subtitle': '세 라이벌을 차례로 이겨 봐요. 라이벌마다 3판 2선승!',
  'tournament.state.locked': '잠김',
  'tournament.state.available': '도전 가능',
  'tournament.state.inProgress': '진행 중',
  'tournament.state.cleared': '클리어!',
  'tournament.lockedHint': '앞 라이벌을 이기면 열려요.',
  'tournament.reward': '보상',
  'tournament.bestOf3': '3판 2선승',
  'tournament.layout': '배치',
  'tournament.challenge': '도전하기',
  'tournament.resume': '이어서 하기',
  'tournament.rechallenge': '다시 도전',
  'tournament.complete': '대회 우승! 세 라이벌을 모두 이겼어요.',
  'tournament.drawNote': '무승부는 승수에 들어가지 않고 다시 겨뤄요.',
  'tournament.round': '{n}라운드',

  // --- series / intermission ----------------------------------------------------
  'series.game': '{n}번째 판',
  'series.you': '나',
  'series.score': '시리즈 스코어',
  'series.firstTo2': '2승 먼저 하면 승리',
  'series.matchPoint': '매치 포인트!',
  'series.won': '시리즈 승리!',
  'series.lost': '시리즈 패배',
  'intermission.title': '다음 판 준비',
  'intermission.rivalSays': '{rival}의 한마디',
  'intermission.hintTitle': '이렇게 바꿔 볼까요?',
  'intermission.next': '다음 판 시작',
  'intermission.quit': '대회 메뉴로',
  'intermission.sameLayout': '같은 배치에서 이어서 겨뤄요.',

  // --- wardrobe -------------------------------------------------------------------
  'wardrobe.title': '옷장',
  'wardrobe.subtitle': '장식은 능력치를 바꾸지 않아요. 마음에 드는 걸로 골라요!',
  'wardrobe.equip': '쓰기',
  'wardrobe.equipped': '착용 중',
  'wardrobe.locked': '잠김',
  'wardrobe.teamNote': '어떤 모자를 써도 팀 문양 배지는 항상 붙어 있어요.',
  'wardrobe.collected': '{n}/{total} 모음',
  'hat.none.name': '맨머리',
  'hat.teamCapA.name': '뾰족 별 비니',
  'hat.teamCapB.name': '동글 달 헬멧',
  'hat.hodadakBand.name': '호다닥 머리띠',
  'hat.tongkeunHat.name': '통큰이 왕실크햇',
  'hat.nunchiMask.name': '눈치왕 눈가리개',
  'hat.none.desc': '바람이 솔솔. 귀가 시원해요.',
  'hat.teamCapA.desc': '별 팀의 기본 모자. 꼭대기 별이 달랑달랑.',
  'hat.teamCapB.desc': '달 팀의 기본 모자. 둥근 고리가 반짝반짝.',
  'hat.hodadakBand.desc': '쓰기만 해도 발이 빨라지는 기분! (기분만요)',
  'hat.tongkeunHat.desc': '은행도 들어갈 것 같은 큰 모자. 통이 커져요.',
  'hat.nunchiMask.desc': '눈치 백 단의 상징. 쉿, 아무도 몰라요.',
  'hat.none.unlock': '처음부터 쓸 수 있어요.',
  'hat.teamCapA.unlock': '처음부터 쓸 수 있어요.',
  'hat.teamCapB.unlock': '처음부터 쓸 수 있어요.',
  'hat.hodadakBand.unlock': '라이벌 대회에서 호다닥을 이기면 얻어요.',
  'hat.tongkeunHat.unlock': '라이벌 대회에서 통큰이를 이기면 얻어요.',
  'hat.nunchiMask.unlock': '라이벌 대회에서 눈치왕을 이기면 얻어요.',

  // --- settings -----------------------------------------------------------------------
  'settings.title': '설정',
  'settings.tab.game': '게임',
  'settings.tab.controls': '조작',
  'settings.tab.audio': '오디오',
  'settings.tab.display': '화면',
  'settings.language': '언어',
  'settings.grabMode': '잡기 방식',
  'settings.grabMode.hold': '누르고 있기',
  'settings.grabMode.toggle': '눌러서 전환',
  'settings.grabMode.desc': '누르고 있기: 버튼을 떼면 손을 놓아요. 전환: 한 번 누르면 잡고, 다시 누르면 놓아요.',
  'settings.tutorialHints': '안내 문구 표시',
  'settings.tutorialHints.desc': '연습과 경기 중 짧은 도움말을 보여 줘요.',
  'settings.controls.action': '행동',
  'settings.controls.keyboard': '키보드',
  'settings.controls.gamepad': '게임패드',
  'settings.controls.pressKey': '키를 누르세요',
  'settings.controls.pressButton': '버튼을 누르세요',
  'settings.controls.unbound': '없음',
  'settings.controls.reset': '기본값으로 되돌리기',
  'settings.controls.resetConfirm.title': '조작을 기본값으로 되돌릴까요?',
  'settings.controls.resetConfirm.body': '바꾼 키와 버튼 설정이 모두 처음으로 돌아가요.',
  'settings.controls.resetConfirm.ok': '되돌리기',
  'settings.controls.hint': '바꿀 칸을 고르고 새 키나 버튼을 눌러요.',
  'settings.controls.swapped': '이미 쓰던 입력이라 「{action}」 칸과 서로 맞바꿨어요.',
  'settings.controls.swappedTag': '맞바꿈',
  'settings.controls.conflict': '같은 입력이 두 행동에 들어 있어요. 둘 중 하나를 바꿔 주세요.',
  'settings.controls.conflictTag': '겹침',
  'settings.audio.master': '전체 음량',
  'settings.audio.music': '음악',
  'settings.audio.sfx': '효과음',
  'settings.audio.ui': '메뉴 소리',
  'settings.subtitles': '자막',
  'settings.subtitles.desc': '중요한 소리를 [사이렌]처럼 글자로도 보여 줘요.',
  'settings.fullscreen': '전체 화면',
  'settings.quality': '그래픽 품질',
  'settings.screenShake': '화면 흔들림',
  'settings.reducedMotion': '움직임 줄이기',
  'settings.reducedMotion.desc': '메뉴 애니메이션과 화면 효과를 줄여요.',
  'settings.uiScale': 'UI 크기',
  'settings.vibration': '진동',
  'quality.low': '낮음',
  'quality.medium': '보통',
  'quality.high': '높음',
  'lang.ko': '한국어',
  'lang.en': 'English',

  // --- controls / actions -------------------------------------------------------------
  'action.moveUp': '위로 이동',
  'action.moveDown': '아래로 이동',
  'action.moveLeft': '왼쪽으로 이동',
  'action.moveRight': '오른쪽으로 이동',
  'action.grab': '잡기 / 놓기',
  'action.dash': '돌진',
  'action.ping': '핑',
  'action.pause': '일시정지',
  'hint.move': '이동',
  'hint.grab': '잡기',
  'hint.release': '놓기',
  'hint.dash': '돌진',
  'hint.ping': '핑',
  'hint.pause': '일시정지',
  'hint.grabHold': '누르고 있는 동안 잡고 있어요.',
  'hint.grabToggle': '한 번 눌러 잡고, 다시 눌러 놓아요.',
  'hint.dashFree': '빈손: 짧게 뛰며 상대를 밀쳐요.',
  'hint.dashCarry': '잡은 상태: 잡은 걸 짧게 휙 가속해요.',
  'hint.pingTarget': '금고·은행을 가리키면 "같이 잡자", 바닥을 가리키면 "이쪽으로".',

  // --- pause ------------------------------------------------------------------------------
  'pause.title': '잠깐 멈춤',
  'pause.resume': '계속',
  'pause.settings': '설정',
  'pause.restart': '다시 시작',
  'pause.menu': '메뉴로',
  'pause.restartConfirm.title': '처음부터 다시 할까요?',
  'pause.restartConfirm.body': '이번 경기 점수는 사라져요.',
  'pause.restartConfirm.ok': '다시 시작',
  'pause.menuConfirm.title': '메뉴로 나갈까요?',
  'pause.menuConfirm.body': '진행 중인 경기는 여기서 끝나요.',
  'pause.menuConfirm.ok': '나가기',

  // --- results (doc §12) ------------------------------------------------------------------
  'results.win': '승리!',
  'results.lose': '패배',
  'results.draw': '무승부',
  'results.win.sub': '더 많이 회수했어요!',
  'results.lose.sub': '이번엔 빈손… 다음엔 다른 방법을 써 볼까요?',
  'results.draw.sub': '점수가 똑같아요! 한 판 더?',
  'results.confirmed': '확정 점수',
  'results.biggest': '이번 판의 큰 사건',
  'results.noEvent': '이번 판은 조용히 끝났어요.',
  'results.reason.time': '시간 종료',
  'results.reason.allRecovered': '모든 전리품 회수 완료',
  'results.reason.decided': '역전할 수 없어 조기 종료',
  'results.rematch': '재대결',
  'results.next': '다음 판',
  'results.menu': '메뉴',
  'results.series': '시리즈 {me} : {rival}',
  'results.drawReplay': '무승부는 승수에 들어가지 않아요. 같은 배치로 다시 한 판!',
  'results.reward': '새 모자: {hat}',

  // --- result event phrases (real records only, doc §12) ------------------------------------
  'event.smallRecovered': '작은 금고 회수 +{value}',
  'event.largeRecovered': '큰 금고 회수 +{value}',
  'event.bankWhole': '은행째 회수! 건물 {building} + 금고 {safes} = +{total}',
  'event.bankEmpty': '빈 은행 회수! 건물 +{building}',
  'event.largePulled': '은행에서 큰 금고 {value}점이 빠짐',
  'event.smallPulled': '은행에서 작은 금고 {value}점이 빠짐',
  'event.lastSecondsSmall': '마지막 {sec}초에 작은 금고 회수',
  'event.lastSecondsLarge': '마지막 {sec}초에 큰 금고 회수',
  'event.lastSecondsBank': '마지막 {sec}초에 은행째 회수! +{total}',
  'event.bankStolen': '상대가 끌던 은행을 빼앗아 회수! +{total}',
  'event.stolenSafeRecovered': '은행에서 빼낸 큰 금고를 회수 +{value}',
  'event.fenceBankRecovered': '펜스를 뚫고 은행째 회수! +{total}',
  'event.comeback': '{deficit}점 차를 뒤집은 역전',
  'event.finalCountdownBank': '두 번째 은행 회수로 도주 준비 시작! +{total}',

  // --- HUD (doc §4, §8, §10) ----------------------------------------------------------------
  'hud.confirmed': '확정',
  'hud.carrying': '운반 중',
  'hud.estimate': '예상 {value}',
  'hud.carryNote': '회수해야 확정돼요',
  'hud.bankBreakdown': '건물 {building} + 금고 {safes}',
  'hud.grab': '잡기',
  'hud.release': '놓기',
  'hud.anchored': '{sec}초 당겨서 뽑기',
  'hud.uprooting': '뽑는 중…',
  'hud.dash': '돌진',
  'hud.dashReady': '준비!',
  'hud.ping': '핑',
  'hud.you': '나',
  'hud.ours': '우리',
  'hud.timeLeft': '남은 시간',
  'hud.banks': '은행',
  'hud.bankInPlay': '남아 있음',
  'hud.bankTaken': '{team} 회수',
  'hud.banksCount': '회수 {n}/{total}',
  'hud.practice': '연습',
  'hud.practiceScore': '연습 점수',
  'hud.practiceNote': '대전에는 들어가지 않아요',
  'hud.noLimit': '시간 제한 없음',
  'hud.ping.grabTogether': '같이 잡자',
  'hud.ping.goHere': '이쪽으로',
  'hud.recovering': '회수 중',
  'hud.loaded': '실림',
  'hud.zone': '우리 차',

  // --- banners / popups ---------------------------------------------------------------------
  'banner.escape': '{sec}초 뒤 출발!',
  'banner.escape.sub': '두 은행 모두 회수! 도주 준비',
  'banner.lastBank': '회수하면 도주 준비 시작',
  'banner.go': '출발!',
  'banner.timeUp': '시간 종료',
  'banner.decided': '승부 결정!',
  'banner.allRecovered': '모두 회수!',
  'banner.practiceDone': '연습 완료!',
  'popup.bank': '건물 {building} + 금고 {safes} = +{total}',
  'popup.bankEmpty': '빈 은행 +{total}',

  // --- tutorial / practice (doc §3) ---------------------------------------------------------
  'tutorial.label': '연습',
  'tutorial.skip': '연습 건너뛰기',
  'tutorial.step': '{step}/{total}',
  'tutorial.find': '100점짜리 작은 금고와 우리 도주차를 찾아보세요',
  'tutorial.find.sub': '가져올 건 금고, 가져갈 곳은 우리 차 앞이에요.',
  'tutorial.grabSafe': '작은 금고에 다가가 잡아요',
  'tutorial.grabSafe.sub': '잡기 전에 대상 전체가 반짝여요.',
  'tutorial.bring': '우리 차 앞 회수 구역으로 끌고 와요',
  'tutorial.bring.sub': '회수해야 점수가 확정돼요.',
  'tutorial.recovered': '+100! 이제 확정 점수예요',
  'tutorial.recovered.sub': '확정 점수는 누구도 빼앗을 수 없어요.',
  'tutorial.bankGrab': '이번엔 은행 외벽을 잡아 보세요',
  'tutorial.bankGrab.sub': '금고 말고 벽을 가리키면 은행 전체가 반짝여요.',
  'tutorial.uproot': '3초 동안 당겨서 은행을 뿌리째 뽑아요',
  'tutorial.uproot.sub': '뽑힌 은행은 누구나 끌 수 있어요.',
  'tutorial.fence': '은행 뒤에서 밀어요! 펜스를 뚫고 짧은 길로',
  'tutorial.fence.sub': '앞에서 끌면 내가 먼저 펜스에 막혀요. 은행 뒤로 돌아가 펜스 쪽으로 밀면 약한 펜스가 부서져요.',
  'tutorial.bankRecover': '은행째 회수하면 안의 금고까지 한 번에!',
  'tutorial.bankRecover.sub': '건물 500 + 안에 실린 금고 가치를 함께 받아요.',
  'tutorial.dash': '돌진: 짧게 뛰거나, 잡은 걸 휙 가속해요',
  'tutorial.dash.sub': '돌진은 4초마다 다시 쓸 수 있어요.',
  'tutorial.done': '잘했어요! 이제 입문 봇과 첫 대전',
  'tutorial.done.sub': '연습 점수는 대전에서 0점부터 다시 시작해요.',

  // --- layout preview (doc §9) ---------------------------------------------------------------
  'preview.title': '배치 미리보기',
  'preview.sameInfo': '양 팀 모두 같은 정보를 봐요',
  'preview.legend.zone': '회수 구역',
  'preview.legend.van': '도주차',
  'preview.legend.bank': '은행 · 문 방향',
  'preview.legend.smallSafe': '작은 금고 100',
  'preview.legend.largeSafe': '큰 금고 300',
  'preview.legend.fence': '은행으로 뚫는 펜스',
  'preview.startsIn': '곧 시작해요',
  'preview.skip': '바로 시작',
  'preview.total': '전체 {value}점',

  // --- loading / tips -------------------------------------------------------------------------
  'loading.title': '광장으로 가는 중…',
  'loading.tip': '도움말',
  'tip.1': '금고를 뽑기만 하면 0점! 우리 차 앞까지 가져와야 확정돼요.',
  'tip.2': '은행 바닥에 실린 금고는 은행과 함께 한 번에 회수돼요.',
  'tip.3': '상대가 은행을 끌 때, 문으로 들어가 큰 금고만 쏙 빼 올 수 있어요.',
  'tip.4': '두 은행이 모두 회수되면 도주차가 30초 뒤 출발해요.',
  'tip.5': '돌진은 4초마다! 밀치기와 운반 가속이 같은 돌진을 써요.',
  'tip.6': '같은 팀끼리는 돌진에 넘어지지 않아요.',
  'tip.7': '확정 점수는 절대 깎이지 않아요.',
  'tip.8': '동점이면 무승부예요. 마지막에 닿은 팀이 이기지 않아요.',
  'tip.9': '핑 하나로 "같이 잡자"와 "이쪽으로"를 모두 할 수 있어요.',
  'tip.10': '작은 금고는 좁은 길도 쏙! 은행은 넓은 길로만 다닐 수 있어요.',

  // --- dialogs / toasts --------------------------------------------------------------------------
  'toast.achievement': '업적 달성!',
  'toast.hat': '새 모자를 얻었어요!',
  'toast.hat.body': '옷장에서 바로 써 볼 수 있어요',

  // --- achievements -------------------------------------------------------------------------------
  'ach.FIRST_RECOVERY.name': '첫 회수',
  'ach.FIRST_RECOVERY.desc': '처음으로 전리품을 회수해 점수를 확정했어요.',
  'ach.BANK_WHOLE.name': '뿌리째 털었다',
  'ach.BANK_WHOLE.desc': '은행을 통째로 우리 차 앞까지 회수했어요.',
  'ach.BANK_HEIST_TEAM.name': '둘이 들면 가볍지',
  'ach.BANK_HEIST_TEAM.desc': '2:2에서 동료와 함께 은행을 회수했어요.',
  'ach.STEAL_LARGE.name': '쏙 빼 왔지',
  'ach.STEAL_LARGE.desc': '상대가 옮기던 은행에서 큰 금고를 빼내 회수했어요.',
  'ach.FENCE_BREAKER.name': '길은 내가 낸다',
  'ach.FENCE_BREAKER.desc': '은행으로 펜스를 뚫었어요.',
  'ach.LAST_SECONDS.name': '아슬아슬 막차',
  'ach.LAST_SECONDS.desc': '경기 종료 5초 전 안에 회수를 완료했어요.',
  'ach.COMEBACK.name': '대역전극',
  'ach.COMEBACK.desc': '500점 넘게 뒤지다가 역전승했어요.',
  'ach.BEAT_HODADAK.name': '호다닥 따라잡기',
  'ach.BEAT_HODADAK.desc': '라이벌 대회에서 호다닥을 이겼어요.',
  'ach.BEAT_TONGKEUN.name': '통 크게 이겼다',
  'ach.BEAT_TONGKEUN.desc': '라이벌 대회에서 통큰이를 이겼어요.',
  'ach.BEAT_NUNCHI.name': '눈치 싸움 승리',
  'ach.BEAT_NUNCHI.desc': '라이벌 대회에서 눈치왕을 이겼어요.',
  'ach.TOURNAMENT_CLEAR.name': '광장의 전설',
  'ach.TOURNAMENT_CLEAR.desc': '세 라이벌을 모두 이기고 대회에서 우승했어요.',
  'ach.WARDROBE.name': '멋쟁이 너구리',
  'ach.WARDROBE.desc': '라이벌에게 얻은 모자를 처음으로 써 봤어요.',

  // --- captions (subtitles for sounds; keys match audio SfxId / LoopId) -----------------------------
  'caption.siren': '[사이렌]',
  'caption.unanchorBank': '[기초가 끊기는 소리]',
  'caption.unanchorSafe': '[금고가 뽑히는 소리]',
  'caption.fenceBreak': '[펜스가 부서지는 소리]',
  'caption.scoreBank': '[은행 회수 팡파르]',
  'caption.scoreSmall': '[짤랑! 작은 금고 회수]',
  'caption.scoreLarge': '[쿵! 큰 금고 회수]',
  'caption.dashHit': '[퍽! 부딪히는 소리]',
  'caption.whistleStart': '[시작 호루라기]',
  'caption.hornEnd': '[종료 경적]',
  'caption.knockdown': '[털썩]',
  'caption.strain': '[끄응… 당기는 소리]',
  'caption.safeLoad': '[금고가 실리는 소리]',
  'caption.safeUnload': '[금고가 빠지는 소리]',
  'caption.recoverStart': '[회수 시작]',
  'caption.recoverCancel': '[회수 취소]',
  'caption.countdownBeep': '[삐]',
  'caption.victory': '[승리 음악]',
  'caption.defeat': '[아쉬운 음악]',
  'caption.draw': '[무승부 음악]',
  'caption.ping': '[핑]',
  'caption.eject': '[퐁! 밖으로 나오는 소리]',
  'caption.bump': '[콩]',
  'caption.grab': '[덥석]',
  'caption.release': '[툭]',
  'caption.dash': '[휙]',
  'caption.bankRumble': '[은행이 끌리는 소리]',
  'caption.drag': '[드르륵 끌리는 소리]',
  'caption.sirenLoop': '[사이렌 계속]',

  // --- game flow (integration) -------------------------------------------------------------------
  'name.rivalBot': '상대 봇',
  'event.fenceBroken': '은행으로 펜스를 뚫어 지름길이 열림',
  'tutorial.wander': '반짝이는 목표 쪽으로 가 봐요. 화살표가 길을 알려 줘요.',
  'tutorial.wanderBank': '북쪽 문으로 나가 화살표를 따라 은행 뒤로 돌아가요.',
  'tutorial.regrab': '은행 외벽을 다시 잡아요. 놓으면 은행이 멈춰요.',
  'tutorial.frontPull': '앞에서 끌면 내가 먼저 펜스에 막혀요. 은행 뒤로 돌아가서 밀어 봐요.',
  'tutorial.offer.title': '연습 끝! 진짜 대전 해 볼까요?',
  'tutorial.offer.body': '입문 호다닥과 수집 광장에서 1:1로 겨뤄요. 점수는 0점부터 시작해요.',
  'tutorial.offer.match': '입문 봇과 첫 대전',
  'tutorial.offer.menu': '메뉴로',
  'firstRun.title': '처음 왔군요, 반가워요',
  'firstRun.body': '50초짜리 연습으로 잡기·운반·회수를 먼저 익혀 볼까요? 언제든 건너뛸 수 있어요.',
  'firstRun.ok': '연습하기',
  'firstRun.later': '메뉴 둘러보기',
  'error.title': '앗, 뭔가 삐끗했어요',
  'error.body': '게임은 그대로 있어요. 다시 시도하거나 메뉴로 돌아가요.',
  'error.retry': '다시 시도',
  'error.menu': '메뉴로',
  'error.detail': '게임은 그대로 있어요. 다시 시도하거나 메뉴로 돌아가요. (오류: {message})',
  'tournament.abandon.title': '진행 중인 시리즈를 그만둘까요?',
  'tournament.abandon.body': '{rival} 시리즈의 승패 기록이 사라져요. 이긴 라이벌은 그대로 남아요.',
  'tournament.abandon.ok': '그만두고 시작',
  'tournament.lockedPick': '앞 라이벌을 먼저 이겨야 해요.',
  'adapt.none.hodadak': '작전? 그런 거 없어! 이번에도 그냥 호다닥 달린다~',
  'adapt.none.tongkeun': '바꿀 거 없지. 이번에도 은행째 통 크게 간다!',
  'adapt.none.nunchi': '음~ 이번엔 하던 대로 할래. 눈치는 계속 보겠지만?',
  'results.nextRival': '다음 라이벌',
  'results.toLadder': '대회 메뉴로',
  'tournament.forfeit.body': '라이벌전 도중에 나가면 이 판은 패배로 기록돼요.',
  'police.dispatched.kicker': '경보가 울렸어요!',
  'police.dispatched.title': '경찰 출동!',
  'police.dispatched.body': '금고나 은행을 든 너구리를 쫓아와요. 대시로 넘어뜨릴 수 있어요.',
} as const;

export type StringKey = keyof typeof ko;
